-- DDL_ALTER_AVIS_ADD_FK_ENTITAT
ALTER TABLE IPA_AVIS
    ADD CONSTRAINT IPA_AVIS_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT(ID);

CREATE INDEX IDX_AVIS_ENTITAT ON IPA_AVIS(ENTITAT_ID);

-- Afegir ENTITAT_ACTUAL a IPA_USUARI
ALTER TABLE IPA_USUARI ADD COLUMN ENTITAT_ACTUAL NUMERIC(38,0);

-- Clau forana per a IPA_USUARI
ALTER TABLE IPA_USUARI
    ADD CONSTRAINT IPA_USUARI_ENTITAT_ACTUAL_FK FOREIGN KEY (ENTITAT_ACTUAL) REFERENCES IPA_ENTITAT(ID);

CREATE INDEX IDX_USUARI_ENTITAT_ACTUAL ON IPA_USUARI(ENTITAT_ACTUAL);