-- Changeset db/changelog/changes/0.9.94/945.yaml::11651146740000-3::limit
CREATE TABLE IPA_PROCESSOS_INICIALS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, CODI VARCHAR(100) NOT NULL, INIT BOOLEAN NOT NULL, CONSTRAINT IPA_PROCESSOS_INICIALS_PK PRIMARY KEY (ID));

ALTER TABLE ipa_config ADD entitat_codi VARCHAR(64);
ALTER TABLE ipa_config ADD configurable BOOLEAN DEFAULT FALSE;

-- Changeset db/changelog/changes/0.9.94/1111.yaml::1651146740001-1::limit
ALTER TABLE ipa_expedient_peticio ADD pendent_canvi_estat_dis BOOLEAN DEFAULT FALSE;
ALTER TABLE ipa_expedient_peticio ADD reintents_canvi_estat_dis SMALLINT DEFAULT 0;

-- Changeset db/changelog/changes/0.9.94/1119.yaml::1659009409606-1::limit
ALTER TABLE ipa_hist_exp_interessat ALTER COLUMN  interessat_doc_num DROP NOT NULL;