CREATE TABLE IPA_METAEXP_TASCA
(
  ID                   bigint               NOT NULL,
  CODI                 character varying(64)			NOT NULL,
  NOM                  character varying(256)	    NOT NULL,
  DESCRIPCIO           character varying(1024)		NOT NULL,
  RESPONSABLE          character varying(64),
  ACTIVA               boolean			NOT NULL,
  CREATEDDATE          timestamp without time zone,
  CREATEDBY_CODI       character varying(64),
  LASTMODIFIEDDATE     timestamp without time zone,
  LASTMODIFIEDBY_CODI  character varying(64),
  META_EXPEDIENT_ID    bigint               NOT NULL
);

ALTER TABLE ONLY IPA_METAEXP_TASCA ADD CONSTRAINT IPA_METAEXP_TASCA_PK PRIMARY KEY (ID);
ALTER TABLE ONLY IPA_METAEXP_TASCA ADD CONSTRAINT IPA_METAEXP_TASCA_MULT_UK UNIQUE (CODI, META_EXPEDIENT_ID);

ALTER TABLE IPA_METAEXP_TASCA ADD CONSTRAINT IPA_METAEXP_METAEXPTAS_FK FOREIGN KEY (META_EXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT (ID);
ALTER TABLE IPA_METAEXP_TASCA ADD CONSTRAINT IPA_USUCRE_METAEXPTAS_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES IPA_USUARI (CODI);
ALTER TABLE IPA_METAEXP_TASCA ADD CONSTRAINT IPA_USUMOD_METAEXPTAS_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES IPA_USUARI (CODI);




	
 CREATE TABLE IPA_EXPEDIENT_TASCA
(
  ID BIGINT NOT NULL,
  EXPEDIENT_IDBIGINT NOT NULL,
  METAEXP_TASCA_ID BIGINT NOT NULL,
  RESPONSABLE_CODI  CHARACTER VARYING(64) NOT NULL, 
  DATA_INICI TIMESTAMP WITHOUT TIMEZONE NOT NULL, 
  DATA_FI TIMESTAMP WITHOUT TIMEZONE, 
  ESTAT CHARACTER VARYING(20),
  MOTIU_REBUIG CHARACTER VARYING(1024),
  CREATEDDATE          TIMESTAMP WITHOUT TIMEZONE,
  CREATEDBY_CODI        CHARACTER VARYING(64),
  LASTMODIFIEDDATE     TIMESTAMP WITHOUT TIMEZONE,
  LASTMODIFIEDBY_CODI   CHARACTER VARYING(64)
);

ALTER TABLE IPA_EXPEDIENT_TASCA ADD CONSTRAINT IPA_EXP_TASCA_PK PRIMARY KEY (ID);
ALTER TABLE IPA_EXPEDIENT_TASCA ADD CONSTRAINT IPA_EXP_EXPTASC_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT(ID);
ALTER TABLE IPA_EXPEDIENT_TASCA ADD CONSTRAINT IPA_METAEXPTASCA_EXPTASC_FK FOREIGN KEY (METAEXP_TASCA_ID) REFERENCES IPA_METAEXP_TASCA(ID);
ALTER TABLE IPA_EXPEDIENT_TASCA ADD CONSTRAINT IPA_USUARI_EXPTASC_FK FOREIGN KEY (RESPONSABLE_CODI) REFERENCES IPA_USUARI(CODI);

