CREATE TABLE IPA_METAEXP_TASCA
(
  ID                   NUMBER(19)           NOT NULL,
  CODI                 VARCHAR2(64)			NOT NULL,
  NOM                  VARCHAR2(256)	    NOT NULL,
  DESCRIPCIO           VARCHAR2(1024)		NOT NULL,
  RESPONSABLE          VARCHAR2(64),
  ACTIVA               NUMBER(1)			NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  META_EXPEDIENT_ID    NUMBER(19)               NOT NULL
);

ALTER TABLE IPA_METAEXP_TASCA ADD (
  CONSTRAINT IPA_METAEXP_TASCA_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_METAEXP_TASCA_MULT_UK UNIQUE (CODI, META_EXPEDIENT_ID));

ALTER TABLE IPA_METAEXP_TASCA ADD (
  CONSTRAINT IPA_METAEXP_METAEXPTAS_FK FOREIGN KEY (META_EXPEDIENT_ID) 
    REFERENCES IPA_METAEXPEDIENT (ID),
  CONSTRAINT IPA_USUCRE_METAEXPTAS_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_USUMOD_METAEXPTAS_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));
    

CREATE TABLE IPA_EXPEDIENT_TASCA
(
  ID NUMBER(19) NOT NULL,
  EXPEDIENT_ID NUMBER(19) NOT NULL,
  METAEXP_TASCA_ID NUMBER(19) NOT NULL,
  RESPONSABLE_CODI  VARCHAR2(64) NOT NULL, 
  DATA_INICI TIMESTAMP(6) NOT NULL, 
  DATA_FI TIMESTAMP(6), 
  ESTAT VARCHAR2(20),
  MOTIU_REBUIG VARCHAR2(1024),
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64)
);

ALTER TABLE IPA_EXPEDIENT_TASCA ADD (CONSTRAINT IPA_EXP_TASCA_PK PRIMARY KEY (ID));
ALTER TABLE IPA_EXPEDIENT_TASCA ADD (CONSTRAINT IPA_EXP_EXPTASC_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT(ID));
ALTER TABLE IPA_EXPEDIENT_TASCA ADD (CONSTRAINT IPA_METAEXPTASCA_EXPTASC_FK FOREIGN KEY (METAEXP_TASCA_ID) REFERENCES IPA_METAEXP_TASCA(ID));
ALTER TABLE IPA_EXPEDIENT_TASCA ADD (CONSTRAINT IPA_USUARI_EXPTASC_FK FOREIGN KEY (RESPONSABLE_CODI) REFERENCES IPA_USUARI(CODI));
	