-- 1421
ALTER TABLE ipa_execucio_massiva ADD document_nom VARCHAR2(256 CHAR);

-- 1516
ALTER TABLE ipa_expedient ADD prioritat VARCHAR2(16 CHAR) DEFAULT 'B_NORMAL';
ALTER TABLE ipa_expedient ADD prioritat_motiu VARCHAR2(1024 CHAR);

-- 1507
ALTER TABLE ipa_expedient_tasca ADD prioritat VARCHAR2(16 CHAR) DEFAULT 'B_NORMAL';
ALTER TABLE ipa_expedient_tasca ADD duracio NUMBER(19,0) DEFAULT 10;

ALTER TABLE ipa_metaexp_tasca ADD prioritat VARCHAR2(16 CHAR) DEFAULT 'B_NORMAL';
ALTER TABLE ipa_metaexp_tasca ADD duracio NUMBER(19,0) DEFAULT 10;

-- 1532
ALTER TABLE IPA_INTERESSAT MODIFY organ_nom VARCHAR2(256 CHAR);

-- 1534
CREATE TABLE IPA_EXPEDIENT_TASCA_OBSE (TASCA_ID NUMBER(38, 0) NOT NULL, OBSERVADOR_CODI VARCHAR2(64 CHAR) NOT NULL, CONSTRAINT ipa_expedient_tascaobse_fk FOREIGN KEY (OBSERVADOR_CODI) REFERENCES IPA_USUARI(CODI), CONSTRAINT ipa_expedient_obse_tasca_fk FOREIGN KEY (TASCA_ID) REFERENCES IPA_EXPEDIENT_TASCA(ID));

ALTER TABLE IPA_EXPEDIENT_TASCA_OBSE ADD CONSTRAINT ipa_expedient_tasca_obse_pk PRIMARY KEY (TASCA_ID, OBSERVADOR_CODI);

ALTER TABLE IPA_EXPEDIENT_TASCA ADD DELEGAT VARCHAR2(64 CHAR);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_EXPEDIENT_TASCA_OBSE TO www_ripea;

-- 1541
ALTER TABLE ipa_usuari ADD vista_moure_actual VARCHAR2(16 CHAR) DEFAULT 'LLISTA';
