import React from 'react';
import { useNavigate, useHref } from 'react-router-dom';
import Box from '@mui/material/Box';
import { GridRow as MuiGridRow } from '@mui/x-data-grid-pro';
import { useBaseAppContext } from '../../BaseAppContext';

type DataGridRowProps = any & {
    isRowLinkActive: (row: any) => boolean;
    isRowClickActive: (row: any) => boolean;
    linkType?: 'OVERLAY' | 'NESTED' | 'MOUSE_EVENTS';
};

const OverlayLink: React.FC<{ linkTo: string; row: React.ReactElement }> = (props) => {
    const { linkTo, row } = props;
    const { getLinkComponent } = useBaseAppContext();
    const Link = getLinkComponent();
    return (
        <div style={{ position: 'relative' }}>
            <Link
                to={linkTo}
                style={{
                    position: 'absolute',
                    inset: 0,
                    zIndex: 1,
                    pointerEvents: 'none',
                }}
            />
            {row}
        </div>
    );
};

const NestedLink: React.FC<{ linkTo: string; row: React.ReactElement }> = (props) => {
    const { linkTo, row } = props;
    const { getLinkComponent } = useBaseAppContext();
    const Link = getLinkComponent();
    return (
        <Box
            component={Link}
            to={linkTo}
            sx={{
                color: 'inherit',
                textDecoration: 'inherit',
            }}>
            {row}
        </Box>
    );
};

const MouseEventsLink: React.FC<{ linkTo: string; row: React.ReactElement }> = (props) => {
    const { linkTo, row } = props;
    const navigate = useNavigate();
    const href = useHref(linkTo);
    const isFromInteractiveElement = (event: React.MouseEvent<HTMLDivElement>) => {
        const target = event.target as any;
        return target.closest('.MuiButtonBase-root') || target.closest('.MuiCheckbox-root');
    };
    const handleMouseDown = (event: React.MouseEvent<HTMLDivElement>) => {
        if (isFromInteractiveElement(event)) return;
        // Botó central
        if (event.button === 1) {
            event.preventDefault();
            window.open(href, '_blank', 'noopener,noreferrer');
        }
    };
    const handleClick = (event: React.MouseEvent<HTMLDivElement>) => {
        if (isFromInteractiveElement(event)) return;
        // Ctrl (Win/Linux) o Cmd (Mac)
        if (event.ctrlKey || event.metaKey) {
            event.preventDefault();
            window.open(href, '_blank', 'noopener,noreferrer');
            return;
        }
        // Click normal → SPA navigation
        navigate(linkTo);
    };
    return (
        <Box
            onClick={handleClick}
            onMouseDown={handleMouseDown}
            role="link"
            tabIndex={0}
            sx={{
                color: 'inherit',
                textDecoration: 'inherit',
            }}>
            {row}
        </Box>
    );
};

const DataGridRow: React.FC<DataGridRowProps> = (props) => {
    const { linkTo, isRowLinkActive, isRowClickActive, linkType, rowId, style, ...otherProps } =
        props;
    const processedLinkTo = linkTo?.replace('{{id}}', '' + rowId);
    const autoGeneratedRow = otherProps.row.id == null;
    const linkActive =
        linkTo != null && !autoGeneratedRow && (isRowLinkActive?.(otherProps.row) ?? true);
    const row = (
        <MuiGridRow
            rowId={rowId}
            style={{ cursor: linkActive || isRowClickActive ? 'pointer' : undefined, ...style }}
            {...otherProps}
        />
    );
    if (linkActive) {
        switch (linkType) {
            case 'OVERLAY':
                return <OverlayLink linkTo={processedLinkTo} row={row} />;
            case 'NESTED':
                return <NestedLink linkTo={processedLinkTo} row={row} />;
            default:
                return <MouseEventsLink linkTo={processedLinkTo} row={row} />;
        }
    } else {
        return row;
    }
};

export default DataGridRow;
