CREATE TABLE IPA_METAEXP_DOMINI
(
  ID                   BIGSERIAL(19)           		NOT NULL,
  CODI                 CHARACTER VARYING(64)		NOT NULL,
  NOM                  CHARACTER VARYING(256)	    NOT NULL,
  DESCRIPCIO           CHARACTER VARYING(1024),
  ENTITAT_ID		   BIGSERIAL(19)				NOT NULL,
  CREATEDDATE          TIMESTAMP WITHOUT TIMEZONE(6),
  CREATEDBY_CODI       CHARACTER VARYING(64),
  LASTMODIFIEDDATE     TIMESTAMP WITHOUT TIMEZONE(6),
  LASTMODIFIEDBY_CODI  CHARACTER VARYING(64),
  META_EXPEDIENT_ID    BIGSERIAL(19)               	NOT NULL
);

ALTER TABLE ONLY IPA_METAEXP_DOMINI ADD CONSTRAINT IPA_METAEXP_DOMINI_PK PRIMARY KEY (ID);
ALTER TABLE ONLY IPA_METAEXP_DOMINI_MULT_UK UNIQUE (CODI, META_EXPEDIENT_ID));
  
ALTER TABLE IPA_METAEXP_DOMINI ADD CONSTRAINT IPA_METAEXP_METAEXPDOM_FK FOREIGN KEY (META_EXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT (ID);
ALTER TABLE IPA_METAEXP_DOMINI ADD CONSTRAINT IPA_ENTITAT_METEXP_METAEDOM_Fk FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID);

    
ALTER TABLE IPA_EXPEDIENT ADD METAEXPEDIENT_DOMINI_ID BIGSERIAL(19);

ALTER TABLE IPA_EXPEDIENT ADD CONSTRAINT IPA_METAEXPDOM_EXPEDIENT_FK FOREIGN KEY (METAEXPEDIENT_DOMINI_ID) REFERENCES IPA_METAEXP_DOMINI(ID);
