CREATE TABLE IPA_METAEXP_DOMINI
(
  ID                   NUMBER(19)           NOT NULL,
  CODI                 VARCHAR2(64)			NOT NULL,
  NOM                  VARCHAR2(256)	    NOT NULL,
  DESCRIPCIO           VARCHAR2(1024),
  ENTITAT_ID		   NUMBER(19)			NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  META_EXPEDIENT_ID    NUMBER(19)               NOT NULL
);

ALTER TABLE IPA_METAEXP_DOMINI ADD (
  CONSTRAINT IPA_METAEXP_DOMINI_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_METAEXP_DOMINI_MULT_UK UNIQUE (CODI, META_EXPEDIENT_ID));
  
ALTER TABLE IPA_METAEXP_DOMINI ADD (
  CONSTRAINT IPA_METAEXP_METAEXPDOM_FK FOREIGN KEY (META_EXPEDIENT_ID) 
    REFERENCES IPA_METAEXPEDIENT (ID),
  CONSTRAINT IPA_ENTITAT_METEXP_METAEDOM_Fk FOREIGN KEY (ENTITAT_ID) 
    REFERENCES IPA_ENTITAT (ID));
    
ALTER TABLE IPA_EXPEDIENT ADD METAEXPEDIENT_DOMINI_ID NUMBER(19);

ALTER TABLE IPA_EXPEDIENT ADD ( 
	CONSTRAINT IPA_METAEXPDOM_EXPEDIENT_FK FOREIGN KEY (METAEXPEDIENT_DOMINI_ID) 
    	REFERENCES IPA_METAEXP_DOMINI(ID));   

