ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD NOT_ENV_REGISTRE_DATA DATE;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD NOT_ENV_REGISTRE_NUMERO NUMBER(19);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD NOT_ENV_REGISTRE_NUM_FORMATAT VARCHAR2(50);

ALTER TABLE IPA_DOCUMENT_ENVIAMENT_INTER ADD NOT_ENV_REGISTRE_DATA DATE;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT_INTER ADD NOT_ENV_REGISTRE_NUMERO NUMBER(19);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT_INTER ADD NOT_ENV_REGISTRE_NUM_FORMATAT VARCHAR2(50);