CREATE TABLE IPA_TIPUS_DOCUMENTAL
(
  ID                   BIGSERIAL(19)           		NOT NULL,
  CODI                 CHARACTER VARYING(64)		NOT NULL,
  NOM                  CHARACTER VARYING(256)	    NOT NULL,
  ENTITAT              BIGSERIAL(19)          		NOT NULL,
  CREATEDDATE          TIMESTAMP WITHOUT TIMEZONE(6),
  CREATEDBY_CODI       CHARACTER VARYING(64),
  LASTMODIFIEDDATE     TIMESTAMP WITHOUT TIMEZONE(6),
  LASTMODIFIEDBY_CODI  CHARACTER VARYING(64)
);

ALTER TABLE ONLY IPA_TIPUS_DOCUMENTAL ADD (
  CONSTRAINT IPA_TIPUS_DOCUMENTAL_PK PRIMARY KEY (ID));

ALTER TABLE ONLY IPA_TIPUS_DOCUMENTAL ADD (
  CONSTRAINT IPA_ENTITAT_TIPUS_DOC_Fk FOREIGN KEY (ENTITAT_ID) 
    REFERENCES IPA_ENTITAT (ID));