-- 937
ALTER TABLE ipa_metaexpedient ADD crear_regla_dist_estat VARCHAR2(10 CHAR);
ALTER TABLE ipa_metaexpedient ADD crear_regla_dist_error VARCHAR2(1024 CHAR);

-- 1030
ALTER TABLE ipa_carpeta ADD expedient_relacionat NUMBER(19);
ALTER TABLE ipa_carpeta ADD CONSTRAINT ipa_carpeta_exprel_fk FOREIGN KEY (expedient_relacionat) REFERENCES ipa_expedient (id);

-- 1033

-- 1039
ALTER TABLE ipa_portafirmes_block_info ADD sign_date TIMESTAMP;

-- 1043
CREATE TABLE IPA_AVIS (ID NUMBER(19) NOT NULL, ASSUMPTE VARCHAR2(256 CHAR) NOT NULL, MISSATGE VARCHAR2(2048 CHAR) NOT NULL, DATA_INICI TIMESTAMP NOT NULL, DATA_FINAL TIMESTAMP NOT NULL, ACTIU NUMBER(1) NOT NULL, AVIS_NIVELL VARCHAR2(10 CHAR) NOT NULL, CREATEDBY_CODI VARCHAR2(64 CHAR), CREATEDDATE TIMESTAMP, LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), LASTMODIFIEDDATE TIMESTAMP, CONSTRAINT IPA_AVIS_PK PRIMARY KEY (ID));
CREATE INDEX IPA_AVIS_DATA_INICI_I ON IPA_AVIS(DATA_INICI);
CREATE INDEX IPA_AVIS_DATA_FINAL_I ON IPA_AVIS(DATA_FINAL);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_AVIS TO WWW_RIPEA;