package es.caib.ripea.service.intf.dto;


public enum ExecucioMassivaTipusDto {
	PORTASIGNATURES,
	CANVI_ESTAT,
	TANCAMENT,
	CUSTODIAR_ELEMENTS_PENDENTS,
	ADJUNTAR_ANNEXOS_PENDENTS,
	ACTUALITZAR_ESTAT_ANOTACIONS,
	FIRMASIMPLEWEB,
	EXPORTAR_ZIP
}

