package es.caib.ripea.service.intf.dto;


public enum ExecucioMassivaTipusDto {
	PORTASIGNATURES,
	CANVI_ESTAT,
	TANCAMENT,
	CUSTODIAR_ELEMENTS_PENDENTS,
	ADJUNTAR_ANNEXOS_PENDENTS,
	ACTUALITZAR_ESTAT_ANOTACIONS,
	FIRMASIMPLEWEB,
	EXPORTAR_ZIP,
	AGAFAR_EXPEDIENT,
	ALLIBERAR_EXPEDIENT,
	RETORNAR_EXPEDIENT,
	SEGUIR_EXPEDIENT,
	UNFOLLOW_EXPEDIENT,
	ESBORRAR_EXPEDIENT,
	EXPORTAR_EXCEL,
	EXPORTAR_CSV,
	EXPORTAR_INDEX_ZIP,
	EXPORTAR_INDEX_PDF,
	EXPORTAR_INDEX_EXCEL,
	EXPORTAR_ENI,
	EXPORTAR_INSIDE
}