--1669 Camp domicili de interessat alineats amb Notib
ALTER TABLE IPA_INTERESSAT MODIFY ADRESA VARCHAR2(250 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_TIPUS VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_TIPUS_VIA VARCHAR2(15 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_NUM_CASA VARCHAR2(5 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_QUAL VARCHAR2(3 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_PUNT_KM VARCHAR2(10 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_AP_CORREUS VARCHAR2(10 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_PORTAL VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_ESCALA VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_PLANTA VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_PORTA VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_BLOC VARCHAR2(50 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_COMPLEMENT VARCHAR2(250 CHAR);
ALTER TABLE IPA_INTERESSAT ADD ADRESSA_POBLACIO VARCHAR2(255 CHAR);