--1729
CREATE TABLE IPA_INTERESSAT_GRUP
(
	ID					NUMBER(19, 0) NOT NULL,
	NOM					VARCHAR2(255 CHAR) NOT NULL,
	DESCRIPCIO			VARCHAR2(1024 CHAR),
	EXPEDIENT_ID		NUMBER(19,0) NOT NULL,
	CREATEDBY_CODI		VARCHAR2(64 CHAR),
	CREATEDDATE			TIMESTAMP,
	LASTMODIFIEDDATE	TIMESTAMP,
	LASTMODIFIEDBY_CODI	VARCHAR2(64 CHAR),
    CONSTRAINT IPA_INTERESSAT_GRUP_PK PRIMARY KEY (ID)
);

ALTER TABLE IPA_INTERESSAT_GRUP ADD CONSTRAINT IPA_INTERESSAT_GRUPEXPED_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT (ID);

CREATE TABLE IPA_INTERESSAT_GRUP_REL
(
	GRUP_ID				NUMBER(19,0) NOT NULL,
	INTERESSAT_ID		NUMBER(19,0) NOT NULL,
    CONSTRAINT IPA_INTERESSAT_GRUP_REL_PK PRIMARY KEY (GRUP_ID, INTERESSAT_ID)
);


ALTER TABLE IPA_INTERESSAT_GRUP_REL ADD CONSTRAINT IPA_INTERESSAT_GRUPREL_INTER_FK FOREIGN KEY (INTERESSAT_ID) REFERENCES IPA_INTERESSAT (ID);
ALTER TABLE IPA_INTERESSAT_GRUP_REL ADD CONSTRAINT IPA_INTERESSAT_GRUPREL_GRUP_FK FOREIGN KEY (GRUP_ID) REFERENCES IPA_INTERESSAT_GRUP (ID);