--1760
ALTER TABLE IPA_ENTITAT ADD LOGO_RIPEA BLOB;
ALTER TABLE IPA_ENTITAT ADD LOGO_MENU BLOB;

ALTER TABLE IPA_ENTITAT ADD BLACK_LOGO_IMG BLOB;
ALTER TABLE IPA_ENTITAT ADD BLACK_LOGO_RIPEA BLOB;
ALTER TABLE IPA_ENTITAT ADD BLACK_LOGO_MENU BLOB;

ALTER TABLE IPA_ENTITAT ADD BLACK_CAPSALERA_COLOR_FONS VARCHAR2(32 CHAR);
ALTER TABLE IPA_ENTITAT ADD BLACK_CAPSALERA_COLOR_LLETRA VARCHAR2(32 CHAR);