--1684
CREATE TABLE IPA_METADOCUMENTFLUX (
    "ID" NUMBER(38,0) NOT NULL ENABLE,
    "METADOCUMENT_ID" NUMBER,
    "PORTAFIRMES_FLUX_ID" VARCHAR2(64 CHAR),
	"PORTAFIRMES_FLUX_DESC" VARCHAR2(256 CHAR),
	"CREATEDBY_CODI" VARCHAR2(64 CHAR), 
	"CREATEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR), 
	"LASTMODIFIEDDATE" TIMESTAMP (6),
	CONSTRAINT "IPA_METADOCUMENTFLUX_PK" PRIMARY KEY ("ID")
);

ALTER TABLE IPA_METADOCUMENTFLUX ADD CONSTRAINT IPA_METADOCUMENT_FK FOREIGN KEY (METADOCUMENT_ID) REFERENCES IPA_METADOCUMENT(ID);

ALTER TABLE IPA_METADOCUMENTFLUX ADD CONSTRAINT IPA_METADOCUMENT_FLUX_UK UNIQUE (METADOCUMENT_ID, PORTAFIRMES_FLUX_ID);

CREATE INDEX IPA_METADOCUMENTFLUX_FK_I ON IPA_METADOCUMENTFLUX ("METADOCUMENT_ID");

--ALTER TABLE IPA_METADOCUMENT DROP COLUMN PORTAFIRMES_FLUXID;