--1660
Insert into IPA_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE,CONFIGURABLE_ORGAN,ORGAN_CODI,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,ENTITAT_CODI,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) 
values ('es.caib.ripea.segonpla.estadistiques.diaries','0 0 1 * * *','Cron per guardar estadistiques del dia actual.','SCHEDULLED','11','0','TEXT',null,null,'0',null,'0','0',null,'0','0');
