--1684
INSERT INTO IPA_METADOCUMENTFLUX (ID, METADOCUMENT_ID, PORTAFIRMES_FLUX_ID, PORTAFIRMES_FLUX_DESC, CREATEDBY_CODI, CREATEDDATE)
SELECT IPA_HIBERNATE_SEQ.NEXTVAL, ID, PORTAFIRMES_FLUXID, 'FLUX_'||PORTAFIRMES_FLUXID, 'SYSTEM', SYSDATE FROM IPA_METADOCUMENT WHERE PORTAFIRMES_FLUXID IS NOT NULL;