ALTER TABLE IPA_INTERESSAT_GRUP_REL DROP CONSTRAINT IPA_INTERESSAT_GRUPREL_INTER_FK;
ALTER TABLE IPA_INTERESSAT_GRUP_REL DROP CONSTRAINT IPA_INTERESSAT_GRUPREL_GRUP_FK;

ALTER TABLE IPA_INTERESSAT_GRUP_REL ADD CONSTRAINT IPA_INTER_GRUPREL_INTER_FK FOREIGN KEY (INTERESSAT_ID) REFERENCES IPA_INTERESSAT (ID);
ALTER TABLE IPA_INTERESSAT_GRUP_REL ADD CONSTRAINT IPA_INTER_GRUPREL_GRUP_FK FOREIGN KEY (GRUP_ID) REFERENCES IPA_INTERESSAT_GRUP (ID);