
CREATE TABLE IPA_ALERTA
(
  ID                   	BIGINT             	NOT NULL,
  TEXT                 	VARCHAR(256)           NOT NULL,
  ERROR                	VARCHAR(2048),
  LLEGIDA              	BIT(1)               NOT NULL,
  CONTINGUT_ID         	BIGINT,
  CREATEDBY_CODI       	VARCHAR(64),
  CREATEDDATE          	TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  	VARCHAR(64),
  LASTMODIFIEDDATE     	TIMESTAMP(6)
);


CREATE TABLE IPA_USUARI
(
  CODI          		VARCHAR(64)            NOT NULL,
  INICIALITZAT  		BIT(1),
  NIF           		VARCHAR(9),
  NOM           		VARCHAR(200),
  EMAIL         		VARCHAR(200),
  IDIOMA				VARCHAR(2) 			NOT NULL,
  VERSION       		BIGINT              NOT NULL
);


CREATE TABLE IPA_ENTITAT
(
  ID                   BIGINT               NOT NULL,
  CODI                 VARCHAR(64)             NOT NULL,
  NOM                  VARCHAR(256)            NOT NULL,
  DESCRIPCIO           VARCHAR(1024),
  CIF                  VARCHAR(9)              NOT NULL,
  UNITAT_ARREL         VARCHAR(9)              NOT NULL,
  ACTIVA               BIT(1),
  VERSION              BIGINT               NOT NULL,
  CREATEDBY_CODI       VARCHAR(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LOGO_IMG BLOB,
  CAPSALERA_COLOR_FONS VARCHAR(32),
  CAPSALERA_COLOR_LLETRA VARCHAR(32)
);


CREATE TABLE IPA_EXP_COMMENT
(
  ID                   BIGINT         NOT NULL,
  EXPEDIENT_ID         BIGINT 				NOT NULL,
  TEXT				   			 VARCHAR (1024),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64)
);

CREATE TABLE IPA_METANODE
(
  ID                   BIGINT               NOT NULL,
  CODI                 VARCHAR(256)            NOT NULL,
  NOM                  VARCHAR(256)            NOT NULL,
  DESCRIPCIO           VARCHAR(1024),
  TIPUS                VARCHAR(256)            NOT NULL,
  ENTITAT_ID           BIGINT               NOT NULL,
  ACTIU                BIT(1),
  VERSION              BIGINT               NOT NULL,
  CREATEDBY_CODI       VARCHAR(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);


CREATE TABLE IPA_METAEXPEDIENT
(
  ID                 BIGINT                 NOT NULL,
  PARE_ID            BIGINT,
  CLASIF_SIA         VARCHAR(30)               NOT NULL,
  SERIE_DOC          VARCHAR(30)               NOT NULL,
  EXPRESSIO_NUMERO   VARCHAR(100),
  NOT_ACTIVA         BIT(1)                  NOT NULL,
);


CREATE TABLE IPA_METAEXP_SEQ
(
  ID                   BIGINT               NOT NULL,
  ANIO                 BIGINT,
  VALOR                BIGINT,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  META_EXPEDIENT_ID    BIGINT               NOT NULL
);


CREATE TABLE IPA_METAEXP_TASCA
(
  ID                   BIGINT           NOT NULL,
  CODI                 VARCHAR(64)			NOT NULL,
  NOM                  VARCHAR(256)	    NOT NULL,
  DESCRIPCIO           VARCHAR(1024)		NOT NULL,
  RESPONSABLE          VARCHAR(64),
  ACTIVA               BIT(1)			NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  META_EXPEDIENT_ID    BIGINT               NOT NULL
);


CREATE TABLE IPA_METADOCUMENT
(
  ID                      BIGINT            NOT NULL,
  MULTIPLICITAT           BIGINT            NOT NULL,
  FIRMA_PFIRMA            BIT(1),
  PORTAFIRMES_DOCTIP      VARCHAR(64),
  PORTAFIRMES_FLUXID      VARCHAR(64),
  PORTAFIRMES_RESPONS     VARCHAR(512),
  PORTAFIRMES_SEQTIP     VARCHAR(256),
  PORTAFIRMES_FLUXTIP     VARCHAR(256),
  PORTAFIRMES_CUSTIP      VARCHAR(64),
  FIRMA_PASSARELA         BIT(1),
  FIRMA_BIOMETRICA 		  BIT(1),
  BIOMETRICA_LECTURA	  BIT(1),
  PASSARELA_CUSTIP        VARCHAR(64),
  PLANTILLA_NOM           VARCHAR(256),
  PLANTILLA_CONTENT_TYPE  VARCHAR(256),
  PLANTILLA_CONTINGUT     BLOB,
  META_EXPEDIENT_ID       BIGINT            NOT NULL,
  NTI_ORIGEN 			  VARCHAR(2)           NOT NULL,
  NTI_ESTELA 			  VARCHAR(4),
  NTI_TIPDOC 			  VARCHAR(4)           NOT NULL,
  META_DOCUMENT_TIPUS_GEN VARCHAR(256)
);


CREATE TABLE IPA_METADADA
(
  ID                    BIGINT              NOT NULL,
  CODI                  VARCHAR(64)            NOT NULL,
  NOM                   VARCHAR(256)           NOT NULL,
  TIPUS                 BIGINT              NOT NULL,
  MULTIPLICITAT         BIGINT              NOT NULL,
  ACTIVA                BIT(1)               NOT NULL,
  READ_ONLY             BIT(1)               NOT NULL,
  ORDRE                 BIGINT              NOT NULL,
  DESCRIPCIO            VARCHAR(1024),
  META_NODE_ID          BIGINT              NOT NULL,
  VERSION               BIGINT              NOT NULL,
  VALOR 				VARCHAR(255),
  CREATEDBY_CODI        VARCHAR(64),
  CREATEDDATE           TIMESTAMP(6),
  LASTMODIFIEDBY_CODI   VARCHAR(64),
  LASTMODIFIEDDATE      TIMESTAMP(6)
);


CREATE TABLE IPA_INTERESSAT
(
  ID                   BIGINT               NOT NULL,
  DTYPE                VARCHAR(256)            NOT NULL,
  NOM                  VARCHAR(30),
  LLINATGE1            VARCHAR(30),
  LLINATGE2            VARCHAR(30),
  DOCUMENT_TIPUS       VARCHAR(40)             NOT NULL,
  DOCUMENT_NUM         VARCHAR(17)             NOT NULL,
  PAIS                 VARCHAR(4),
  PROVINCIA            VARCHAR(2),
  MUNICIPI             VARCHAR(5),
  ADRESA               VARCHAR(160),
  CODI_POSTAL          VARCHAR(5),
  EMAIL                VARCHAR(160),
  TELEFON              VARCHAR(20),
  OBSERVACIONS         VARCHAR(160),
  ORGAN_CODI           VARCHAR(9),
  ORGAN_NOM		       VARCHAR(80),
  RAO_SOCIAL           VARCHAR(80),
  NOT_IDIOMA           VARCHAR(2),
  NOT_AUTORITZAT       BIT(1)                NOT NULL,
  ES_REPRESENTANT      BIT(1)                NOT NULL,
  REPRESENTANT_ID      BIGINT,
  EXPEDIENT_ID         BIGINT               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  VERSION              BIGINT               NOT NULL,
  ENTREGA_DEH 		   BIT(1),
  ENTREGA_DEH_OBLIGAT  BIT(1),
  INCAPACITAT 		   BIT(1)
);


CREATE TABLE IPA_CONTINGUT
(
  ID                   BIGINT               NOT NULL,
  NOM                  VARCHAR(1024)           NOT NULL,
  TIPUS                BIGINT               NOT NULL,
  PARE_ID              BIGINT,
  ESBORRAT             BIGINT,
  ARXIU_UUID           VARCHAR(36),
  ARXIU_DATA_ACT       TIMESTAMP(6),
  EXPEDIENT_ID         BIGINT,
  CONTMOV_ID           BIGINT,
  ENTITAT_ID           BIGINT               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  VERSION              BIGINT               NOT NULL,
  ESBORRAT_DATA 	   TIMESTAMP(6)
);


CREATE TABLE IPA_CONT_MOV
(
  ID                   BIGINT               NOT NULL,
  CONTINGUT_ID         BIGINT               NOT NULL,
  ORIGEN_ID            BIGINT,
  DESTI_ID             BIGINT               NOT NULL,
  REMITENT_CODI        VARCHAR(64),
  COMENTARI            VARCHAR(256),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64)
);


CREATE TABLE IPA_CONT_LOG
(
  ID                   BIGINT               NOT NULL,
  TIPUS                BIGINT               NOT NULL,
  CONTINGUT_ID         BIGINT               NOT NULL,
  PARE_ID              BIGINT,
  CONTMOV_ID           BIGINT,
  OBJECTE_ID           VARCHAR(256),
  OBJECTE_LOG_TIPUS    BIGINT,
  OBJECTE_TIPUS        BIGINT,
  PARAM1               VARCHAR(256),
  PARAM2               VARCHAR(256),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64)
);


CREATE TABLE IPA_NODE
(
  ID                  BIGINT                NOT NULL,
  METANODE_ID         BIGINT
);


CREATE TABLE IPA_CARPETA
(
  ID     BIGINT                             NOT NULL
);


CREATE TABLE IPA_DADA
(
  ID                   BIGINT               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  ORDRE                BIGINT,
  VALOR                VARCHAR(256)            NOT NULL,
  VERSION              BIGINT               NOT NULL,
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  METADADA_ID          BIGINT               NOT NULL,
  NODE_ID              BIGINT               NOT NULL
);


CREATE TABLE IPA_EXPEDIENT
(
  ID                 BIGINT                 NOT NULL,
  ESTAT              BIGINT                 NOT NULL,
  TANCAT_DATA        TIMESTAMP(6),
  TANCAT_MOTIU       VARCHAR(1024),
  ANIO               BIGINT                 NOT NULL,
  SEQUENCIA          BIGINT                 NOT NULL,
  CODI               VARCHAR(256)              NOT NULL,
  NTI_VERSION        VARCHAR(5)                NOT NULL,
  NTI_IDENTIF        VARCHAR(52)               NOT NULL,
  NTI_ORGANO         VARCHAR(9)                NOT NULL,
  NTI_FECHA_APE      TIMESTAMP(6)               NOT NULL,
  NTI_CLASIF_SIA     VARCHAR(30)               NOT NULL,
  METAEXPEDIENT_ID   BIGINT                 NOT NULL,
    METAEXPEDIENT_DOMINI_ID   BIGINT,
  SISTRA_BANTEL_NUM  VARCHAR(16),
  SISTRA_PUBLICAT    BIT(1),
  SISTRA_UNITAT_ADM  VARCHAR(9),
  SISTRA_CLAU        VARCHAR(100),
  AGAFAT_PER_CODI    VARCHAR(64),
  EXPEDIENT_ESTAT_ID BIGINT
);


CREATE TABLE IPA_EXPEDIENT_REL
(
  EXPEDIENT_ID       BIGINT                 NOT NULL,
  EXPEDIENT_REL_ID   BIGINT                 NOT NULL
);


CREATE TABLE IPA_DOCUMENT
(
  ID                   BIGINT               NOT NULL,
  TIPUS                BIGINT               NOT NULL,
  ESTAT                BIGINT               NOT NULL,
  UBICACIO             VARCHAR(255),
  DATA                 TIMESTAMP(6)             NOT NULL,
  DATA_CAPTURA         TIMESTAMP(6)             NOT NULL,
  CUSTODIA_DATA        TIMESTAMP(6),
  CUSTODIA_ID          VARCHAR(256),
  CUSTODIA_CSV         VARCHAR(256),
  FITXER_NOM           VARCHAR(256),
  FITXER_CONTENT_TYPE  VARCHAR(256),
  FITXER_CONTINGUT     BLOB,
  VERSIO_DARRERA       VARCHAR(32),
  VERSIO_COUNT         BIGINT               NOT NULL,
  NTI_VERSION          VARCHAR(5)              NOT NULL,
  NTI_IDENTIF          VARCHAR(48)             NOT NULL,
  NTI_ORGANO           VARCHAR(9)              NOT NULL,
  NTI_ORIGEN           VARCHAR(2)              NOT NULL,
  NTI_ESTELA           VARCHAR(4)              NOT NULL,
  NTI_TIPDOC           VARCHAR(4)              NOT NULL,
  NTI_IDORIG           VARCHAR(48),
  NTI_TIPFIR           VARCHAR(4),
  NTI_CSV              VARCHAR(256),
  NTI_CSVREG           VARCHAR(512)
);


CREATE TABLE IPA_DOCUMENT_ENVIAMENT
(
  ID                   		BIGINT               NOT NULL,
  DTYPE                		VARCHAR(32)             NOT NULL,
  ESTAT                		VARCHAR(255)            NOT NULL,
  ASSUMPTE             		VARCHAR(256)            NOT NULL,
  OBSERVACIONS         		VARCHAR(256),
  ENVIAT_DATA          		TIMESTAMP(6),
  PROCESSAT_DATA       		TIMESTAMP(6),
  CANCELAT_DATA        		TIMESTAMP(6),
  ERROR                		BIT(1),
  ERROR_DESC           		VARCHAR(2048),
  INTENT_NUM           		BIGINT,
  INTENT_DATA          		TIMESTAMP(6),
  INTENT_PROXIM_DATA   		TIMESTAMP(6),
  NOT_TIPUS            		BIGINT,
  NOT_DATA_PROG        		TIMESTAMP(6),
  NOT_RETARD           		BIGINT,
  NOT_DATA_CADUCITAT   		TIMESTAMP(6),
  NOT_ENV_ID           		VARCHAR(100),
  NOT_ENV_REF          		VARCHAR(100),
  NOT_ENV_DAT_ESTAT    		VARCHAR(20),
  NOT_ENV_DAT_DATA     		TIMESTAMP(6),
  NOT_ENV_DAT_ORIG     		VARCHAR(20),
  NOT_ENV_CERT_DATA    		TIMESTAMP(6),
  NOT_ENV_CERT_ORIG    		VARCHAR(20),
  NOT_ENV_CERT_ARXIUID 		VARCHAR(50),
  PF_PRIORITAT         		BIGINT,
  PF_CAD_DATA          		TIMESTAMP(6),
  PF_DOC_TIPUS         		VARCHAR(64),
  PF_RESPONSABLES      		VARCHAR(1024),
  PF_FLUX_TIPUS        		BIGINT,
  PF_FLUX_ID           		VARCHAR(64),
  PF_PORTAFIRMES_ID    		VARCHAR(64),
  PF_CALLBACK_ESTAT    		BIGINT,
  VF_CODI_USUARI 	   		VARCHAR(64),
  VF_TITOL 	 		   		VARCHAR(256),
  VF_DESCRIPCIO 	   		VARCHAR(256),
  VF_CODI_DISPOSITIU   		VARCHAR(64),
  VF_MESSAGE_CODE 	   		VARCHAR(64),
  VF_CALLBACK_ESTAT    		BIGINT,
  VF_CONTRASENYA_USUARI 	VARCHAR(64),
  VF_LECTURA_OBLIGATORIA 	BIT(1),
  VF_VIAFIRMA_DISPOSITIU 	BIGINT,
  PUB_TIPUS            		BIGINT,
  DOCUMENT_ID          		BIGINT               NOT NULL,
  EXPEDIENT_ID         		BIGINT               NOT NULL,
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDDATE     		TIMESTAMP(6),
  CREATEDBY_CODI       		VARCHAR(256),
  LASTMODIFIEDBY_CODI  		VARCHAR(256),
  VERSION              		BIGINT               NOT NULL,
  SERVEI_TIPUS 		   		VARCHAR(10),
  ENTREGA_POSTAL 	  		BIT(1),
  NOTIFICACIO_ESTAT    		VARCHAR(255)
);


CREATE TABLE IPA_DOCUMENT_ENVIAMENT_DOC (
  DOCUMENT_ENVIAMENT_ID BIGINT              NOT NULL,
  DOCUMENT_ID           BIGINT              NOT NULL
);


CREATE TABLE IPA_EXPEDIENT_INTERESSAT
(
  EXPEDIENT_ID   BIGINT                     NOT NULL,
  INTERESSAT_ID  BIGINT                     NOT NULL
);


CREATE TABLE IPA_EXECUCIO_MASSIVA
(
  ID                   BIGINT		NOT NULL,
  TIPUS                VARCHAR(255)	NOT NULL,
  DATA_INICI	       TIMESTAMP(6),
  DATA_FI              TIMESTAMP(6),
  PFIRMES_MOTIU		   VARCHAR(256),
  PFIRMES_PRIORI	   VARCHAR(255),
  PFIRMES_DATCAD	   TIMESTAMP(6),
  ENVIAR_CORREU		   BIT(1),
  ENTITAT_ID		   BIGINT		NOT NULL,
  CREATEDBY_CODI       VARCHAR(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);


CREATE TABLE IPA_MASSIVA_CONTINGUT
(
  ID                   BIGINT		NOT NULL,
  EXECUCIO_MASSIVA_ID  BIGINT,
  CONTINGUT_ID  	   BIGINT,
  DATA_INICI	       TIMESTAMP(6),
  DATA_FI              TIMESTAMP(6),
  ESTAT				   VARCHAR(255),
  ERROR				   VARCHAR(2046),
  ORDRE				   BIGINT,
  CREATEDBY_CODI       VARCHAR(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);


CREATE TABLE IPA_ACL_CLASS
(
  ID     BIGINT                             NOT NULL,
  CLASS  VARCHAR(100)                          NOT NULL
);


CREATE TABLE IPA_ACL_SID
(
  ID         BIGINT                         NOT NULL,
  PRINCIPAL  BIT(1)                          NOT NULL,
  SID        VARCHAR(100)                      NOT NULL
);


CREATE TABLE IPA_ACL_ENTRY
(
  ID                   BIGINT               NOT NULL,
  ACL_OBJECT_IDENTITY  BIGINT               NOT NULL,
  ACE_ORDER            BIGINT               NOT NULL,
  SID                  BIGINT               NOT NULL,
  MASK                 BIGINT               NOT NULL,
  GRANTING             BIT(1)                NOT NULL,
  AUDIT_SUCCESS        BIT(1)                NOT NULL,
  AUDIT_FAILURE        BIT(1)                NOT NULL
);


CREATE TABLE IPA_ACL_OBJECT_IDENTITY
(
  ID                  BIGINT                NOT NULL,
  OBJECT_ID_CLASS     BIGINT                NOT NULL,
  OBJECT_ID_IDENTITY  BIGINT                NOT NULL,
  PARENT_OBJECT       BIGINT,
  OWNER_SID           BIGINT                NOT NULL,
  ENTRIES_INHERITING  BIT(1)                 NOT NULL
);





CREATE TABLE IPA_EXPEDIENT_ESTAT
(
	ID                  BIGINT               			NOT NULL,
	CODI 			    VARCHAR(256)						NOT NULL,
	NOM 			    VARCHAR(256)						NOT NULL,
	ORDRE 			    BIGINT							NOT NULL,
	COLOR 			    VARCHAR(256),					  
    METAEXPEDIENT_ID    BIGINT,               
    INICIAL             BIT(1),
    RESPONSABLE_CODI    VARCHAR(64),
    
	
    CREATEDDATE         TIMESTAMP(6),
    LASTMODIFIEDDATE    TIMESTAMP(6),
    CREATEDBY_CODI      VARCHAR(256),
    LASTMODIFIEDBY_CODI VARCHAR(256)
);




CREATE TABLE IPA_EXPEDIENT_PETICIO
(
  ID                   BIGINT               NOT NULL,
  IDENTIFICADOR        VARCHAR(80)             NOT NULL,
  CLAU_ACCES           VARCHAR(200)            NOT NULL,
  DATA_ALTA            TIMESTAMP(6)             NOT NULL,
  ESTAT			       VARCHAR(40)             NOT NULL,
  META_EXPEDIENT_NOM   VARCHAR(256),
  EXP_PETICIO_ACCIO    VARCHAR(20),
  REGISTRE_ID 		   BIGINT,
  CONSULTA_WS_ERROR    BIT(1),
  CONSULTA_WS_ERROR_DESC  VARCHAR(4000),
  CONSULTA_WS_ERROR_DATE  TIMESTAMP(6),
  NOTIFICA_DIST_ERROR VARCHAR(4000),
  EXPEDIENT_ID 				BIGINT,
  
  CREATEDDATE         TIMESTAMP(6),
  LASTMODIFIEDDATE    TIMESTAMP(6),
  CREATEDBY_CODI      VARCHAR(256),
  LASTMODIFIEDBY_CODI VARCHAR(256)

);



CREATE TABLE IPA_REGISTRE (
  ID 						BIGINT 		NOT NULL, 
  APLICACIO_CODI 			VARCHAR(20), 
  APLICACIO_VERSIO 			VARCHAR(15), 
  ASSUMPTE_CODI_CODI 		VARCHAR(16), 
  ASSUMPTE_CODI_DESC 		VARCHAR(100), 
  ASSUMPTE_TIPUS_CODI		VARCHAR(16), 
  ASSUMPTE_TIPUS_DESC 		VARCHAR(100), 
  DATA 						TIMESTAMP(6) 	NOT NULL, 
  DOC_FISICA_CODI 			VARCHAR(1), 
  DOC_FISICA_DESC 			VARCHAR(100), 
  ENTITAT_CODI 				VARCHAR(21) 	NOT NULL, 
  ENTITAT_DESC 				VARCHAR(100), 
  EXPEDIENT_NUMERO 			VARCHAR(80), 
  EXPOSA 					VARCHAR(4000), 
  EXTRACTE					VARCHAR(240),
  PROCEDIMENT_CODI			VARCHAR(20),
  IDENTIFICADOR 			VARCHAR(100) 	NOT NULL, 
  IDIOMA_CODI 				VARCHAR(2) 	NOT NULL, 
  IDIOMA_DESC 				VARCHAR(100), 
  LLIBRE_CODI 				VARCHAR(4) 	NOT NULL, 
  LLIBRE_DESC 				VARCHAR(100), 
  OBSERVACIONS 				VARCHAR(50), 
  OFICINA_CODI 				VARCHAR(21) 	NOT NULL, 
  OFICINA_DESC 				VARCHAR(100), 
  ORIGEN_DATA 				TIMESTAMP(6), 
  ORIGEN_REGISTRE_NUM 		VARCHAR(80), 
  REF_EXTERNA 				VARCHAR(16), 
  SOLICITA 					VARCHAR(4000), 
  TRANSPORT_NUM 			VARCHAR(20), 
  TRANSPORT_TIPUS_CODI 		VARCHAR(2), 
  TRANSPORT_TIPUS_DESC 		VARCHAR(100), 
  USUARI_CODI 				VARCHAR(20), 
  USUARI_NOM 				VARCHAR(80), 
  DESTI_CODI 				VARCHAR(21) 	NOT NULL, 
  DESTI_DESCRIPCIO 			VARCHAR(100),
  ENTITAT_ID				BIGINT 		NOT NULL,

  CREATEDDATE         TIMESTAMP(6),
  LASTMODIFIEDDATE    TIMESTAMP(6),
  CREATEDBY_CODI      VARCHAR(256),
  LASTMODIFIEDBY_CODI VARCHAR(256)
);


CREATE TABLE IPA_REGISTRE_ANNEX (
	ID 						BIGINT 		NOT NULL, 
	CONTINGUT BLOB,
	FIRMA_CONTINGUT BLOB,
	FIRMA_PERFIL VARCHAR(4),
	FIRMA_TAMANY BIGINT,
	FIRMA_TIPUS VARCHAR(4),
	NOM VARCHAR(80) NOT NULL,
	FIRMA_NOM VARCHAR(80),
	NTI_FECHA_CAPTURA TIMESTAMP(6) NOT NULL,
	NTI_ORIGEN VARCHAR(20) NOT NULL,
	NTI_TIPO_DOC VARCHAR(20) NOT NULL,
	OBSERVACIONS VARCHAR(50),
	SICRES_TIPO_DOC VARCHAR(20)  NOT NULL,
	SICRES_VALIDEZ_DOC VARCHAR(30),
	TAMANY BIGINT NOT NULL,
	TIPUS_MIME VARCHAR(30),
	TITOL VARCHAR(200) NOT NULL,
	UUID VARCHAR(100),
	REGISTRE_ID BIGINT NOT NULL,
	ESTAT VARCHAR(20),
	ERROR VARCHAR(4000),
	NTI_ESTADO_ELABORACIO VARCHAR(50) NOT NULL,
	
	CREATEDDATE         TIMESTAMP(6),
  	LASTMODIFIEDDATE    TIMESTAMP(6),
  	CREATEDBY_CODI      VARCHAR(256),
  	LASTMODIFIEDBY_CODI VARCHAR(256)
);


CREATE TABLE IPA_REGISTRE_INTERESSAT 
  ( 
     ID                  BIGINT NOT NULL, 
     ADRESA              VARCHAR(160), 
     CANAL               VARCHAR(30), 
     CP                  VARCHAR(5), 
     DOC_NUMERO          VARCHAR(17), 
     DOC_TIPUS           VARCHAR(15), 
     EMAIL               VARCHAR(160), 
     LLINATGE1           VARCHAR(30), 
     LLINATGE2           VARCHAR(30), 
     MUNICIPI_CODI       VARCHAR(100), 
     NOM                 VARCHAR(30), 
     OBSERVACIONS        VARCHAR(160), 
     PAIS_CODI           VARCHAR(4), 
     PROVINCIA_CODI      VARCHAR(100), 
     RAO_SOCIAL          VARCHAR(80), 
     TELEFON             VARCHAR(20), 
     TIPUS               VARCHAR(40) NOT NULL, 
     REPRESENTANT_ID     BIGINT, 
     REGISTRE_ID         BIGINT, 
     PAIS                VARCHAR(200), 
     PROVINCIA           VARCHAR(200), 
     MUNICIPI            VARCHAR(200), 
     ORGAN_CODI          VARCHAR(9), 
     CREATEDDATE         TIMESTAMP(6), 
     LASTMODIFIEDDATE    TIMESTAMP(6), 
     CREATEDBY_CODI      VARCHAR(256), 
     LASTMODIFIEDBY_CODI VARCHAR(256) 
  ); 

CREATE TABLE IPA_DOCUMENT_ENVIAMENT_INTER
(
  ID                   	BIGINT NOT NULL,
  DOCUMENT_ENVIAMENT_ID BIGINT NOT NULL,
  INTERESSAT_ID 		BIGINT NOT NULL,
  NOT_ENV_REF   		VARCHAR(100),
  CREATEDBY_CODI       VARCHAR(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  NOT_ENV_DAT_ESTAT    		VARCHAR(20),
  NOT_ENV_DAT_DATA     		TIMESTAMP(6),
  NOT_ENV_DAT_ORIG     		VARCHAR(20),
  NOT_ENV_CERT_DATA    		TIMESTAMP(6),
  NOT_ENV_CERT_ORIG    		VARCHAR(20),
  ERROR                		BIT(1),
  ERROR_DESC           		VARCHAR(2048)
);

CREATE TABLE IPA_VIAFIRMA_USUARI (
	CODI			VARCHAR(64)			NOT NULL,
	CONTRASENYA		VARCHAR(64)			NOT NULL,
	DESCRIPCIO		VARCHAR(64)			NOT NULL
);

CREATE TABLE IPA_USUARI_VIAFIRMA_RIPEA (
    ID                    BIGINT            NOT NULL,
    VIAFIRMA_USER_CODI    VARCHAR(64)          NOT NULL,
    RIPEA_USER_CODI       VARCHAR(64)          NOT NULL
);

CREATE TABLE IPA_DOCUMENT_ENVIAMENT_DIS (
    ID                      BIGINT               NOT NULL,
    CODI                    VARCHAR(64),
    CODI_APLICACIO          VARCHAR(64),
    CODI_USUARI             VARCHAR(64),
    DESCRIPCIO              VARCHAR(255),
    LOCALE                  VARCHAR(10),
    ESTAT                   VARCHAR(64),
    TOKEN                   VARCHAR(255),
    IDENTIFICADOR           VARCHAR(64),
    TIPUS                   VARCHAR(64),
    EMAIL_USUARI            VARCHAR(64),
    IDENTIFICADOR_NAC       VARCHAR(64),
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDDATE        TIMESTAMP(6),
    CREATEDBY_CODI          VARCHAR(256),
    LASTMODIFIEDBY_CODI     VARCHAR(256)
);

 CREATE TABLE IPA_EXPEDIENT_TASCA
(
  ID BIGINT NOT NULL,
  EXPEDIENT_ID BIGINT NOT NULL,
  METAEXP_TASCA_ID BIGINT NOT NULL,
  RESPONSABLE_CODI  VARCHAR(64) NOT NULL, 
  DATA_INICI TIMESTAMP(6) NOT NULL, 
  DATA_FI TIMESTAMP(6), 
  ESTAT VARCHAR(20),
  MOTIU_REBUIG VARCHAR(1024),
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR(64)
);


ALTER TABLE IPA_ALERTA ADD PRIMARY KEY (ID);
ALTER TABLE IPA_ENTITAT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_EXP_COMMENT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METANODE ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METAEXPEDIENT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METAEXP_SEQ ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METAEXP_TASCA ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METADOCUMENT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_METADADA ADD PRIMARY KEY (ID);
ALTER TABLE IPA_INTERESSAT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_CONTINGUT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_EXPEDIENT ADD PRIMARY KEY (ID);
ALTER TABLE IPA_ACL_CLASS ADD PRIMARY KEY (ID);
ALTER TABLE IPA_ACL_SID ADD PRIMARY KEY (ID);
ALTER TABLE IPA_ACL_ENTRY ADD PRIMARY KEY (ID);
ALTER TABLE IPA_ACL_OBJECT_IDENTITY ADD PRIMARY KEY (ID);
ALTER TABLE IPA_CONT_LOG ADD PRIMARY KEY (ID);


ALTER TABLE IPA_ALERTA ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_ENTITAT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_EXP_COMMENT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METANODE ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METAEXPEDIENT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METAEXP_SEQ ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METAEXP_TASCA ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METADOCUMENT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_METADADA ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_INTERESSAT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_CONTINGUT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_EXPEDIENT ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_ACL_CLASS ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_ACL_SID ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_ACL_ENTRY ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_ACL_OBJECT_IDENTITY ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);
ALTER TABLE IPA_CONT_LOG ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY(START WITH 1);




--INSERT INTO IPA_USUARI (CODI, INICIALITZAT,NIF, NOM, EMAIL,  IDIOMA, VERSION) VALUES ('user', true, 'NIF', 'user', 'user@mail.com', 'CA', 0);
--INSERT INTO IPA_USUARI (CODI, INICIALITZAT,NIF, NOM, EMAIL,  IDIOMA, VERSION) VALUES ('admin', true, 'NIF', 'admin', 'admin@mail.com', 'CA', 0);

