----------------PER ID DE OBJECTE------------------------------------

SELECT ACE_ORDER
     , MASK
     , PRINCIPAL
     , SID.SID
     , CLASS
FROM IPA_ACL_OBJECT_IDENTITY OBJ
   , IPA_ACL_ENTRY ENT
   , IPA_ACL_SID SID
   , IPA_ACL_CLASS CLA
WHERE CLA.ID=OBJ.OBJECT_ID_CLASS
  AND OBJ.ID=ENT.ACL_OBJECT_IDENTITY
  AND ENT.SID=SID.ID
  AND OBJ.OBJECT_ID_IDENTITY IN (3102, 3101, 3108);
  
----------------PER USUARI------------------------------------
  
SELECT
       CASE WHEN BITAND(ENT.MASK, 1)   != 0 THEN 'READ' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 2)   != 0 THEN 'WRITE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 4)   != 0 THEN 'CREATE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 8)   != 0 THEN 'DELETE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 16)  != 0 THEN 'ADMINISTRATION' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 32)  != 0 THEN 'STATISTICS' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 64)  != 0 THEN 'COMU' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 128) != 0 THEN 'ADM_COMU' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 256) != 0 THEN 'DISSENY' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 512) != 0 THEN 'ADM_LECTURA' ELSE '' END
       AS PERMISOS
     , SID.PRINCIPAL
     , SID.SID
     , CLA.CLASS
     , OBJ.OBJECT_ID_IDENTITY
     , CASE WHEN CLA.CLASS LIKE '%EntitatEntity' THEN (SELECT CODI||' - '||NOM FROM IPA_ENTITAT WHERE ID=OBJ.OBJECT_ID_IDENTITY) ELSE '' END ||
       CASE WHEN CLA.CLASS LIKE '%GrupEntity' THEN (SELECT DESCRIPCIO FROM IPA_GRUP WHERE ID=OBJ.OBJECT_ID_IDENTITY) ELSE '' END ||
       CASE WHEN CLA.CLASS LIKE '%MetaNodeEntity' THEN (SELECT CODI||' - '||NOM FROM IPA_METANODE WHERE ID=OBJ.OBJECT_ID_IDENTITY) ELSE '' END ||
       CASE WHEN CLA.CLASS LIKE '%OrganGestorEntity' THEN (SELECT CODI||' - '||NOM FROM IPA_ORGAN_GESTOR WHERE ID=OBJ.OBJECT_ID_IDENTITY) ELSE '' END ||
       CASE WHEN CLA.CLASS LIKE '%MetaExpedientOrganGestorEntity' THEN (SELECT IMN.CODI||' - '||IMN.NOM||' + '||IOG.CODI||' - '||IOG.NOM FROM IPA_METAEXP_ORGAN IME, IPA_METANODE IMN, IPA_ORGAN_GESTOR IOG WHERE IME.META_EXPEDIENT_ID=IMN.ID AND IME.ORGAN_GESTOR_ID=IOG.ID AND IME.ID=OBJ.OBJECT_ID_IDENTITY) ELSE '' END AS OBJECTE_NOM
FROM IPA_ACL_OBJECT_IDENTITY OBJ
   , IPA_ACL_ENTRY ENT
   , IPA_ACL_SID SID
   , IPA_ACL_CLASS CLA
WHERE CLA.ID=OBJ.OBJECT_ID_CLASS
  AND OBJ.ID=ENT.ACL_OBJECT_IDENTITY
  AND ENT.SID=SID.ID
  AND ((SID.PRINCIPAL=1 AND SID.SID='rip_user2') or (SID.PRINCIPAL=0 AND SID.SID IN ('tothom')))
  ORDER BY CLA.CLASS, OBJ.OBJECT_ID_IDENTITY, PERMISOS;