----------------PER ID DE OBJECTE------------------------------------

SELECT ACE_ORDER
     , MASK
     , PRINCIPAL
     , SID.SID
     , CLASS
FROM IPA_ACL_OBJECT_IDENTITY OBJ
   , IPA_ACL_ENTRY ENT
   , IPA_ACL_SID SID
   , IPA_ACL_CLASS CLA
WHERE CLA.ID=OBJ.OBJECT_ID_CLASS
  AND OBJ.ID=ENT.ACL_OBJECT_IDENTITY
  AND ENT.SID=SID.ID
  AND OBJ.OBJECT_ID_IDENTITY IN (3102, 3101, 3108);
  
----------------PER USUARI------------------------------------
  
SELECT ENT.ACE_ORDER,
       CASE WHEN BITAND(ENT.MASK, 1)   != 0 THEN 'READ' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 2)   != 0 THEN 'WRITE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 4)   != 0 THEN 'CREATE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 8)   != 0 THEN 'DELETE' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 16)  != 0 THEN 'ADMINISTRATION' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 32)  != 0 THEN 'STATISTICS' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 64)  != 0 THEN 'COMU' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 128) != 0 THEN 'ADM_COMU' ELSE '' END ||
       CASE WHEN BITAND(ENT.MASK, 256) != 0 THEN 'DISSENY' ELSE '' END
       AS PERMISOS
     , SID.PRINCIPAL
     , SID.SID
     , CLA.CLASS
     , OBJ.OBJECT_ID_IDENTITY
FROM IPA_ACL_OBJECT_IDENTITY OBJ
   , IPA_ACL_ENTRY ENT
   , IPA_ACL_SID SID
   , IPA_ACL_CLASS CLA
WHERE CLA.ID=OBJ.OBJECT_ID_CLASS
  AND OBJ.ID=ENT.ACL_OBJECT_IDENTITY
  AND ENT.SID=SID.ID
  AND ((SID.PRINCIPAL=1 AND SID.SID='rip_user') or (SID.PRINCIPAL=0 AND SID.SID='tothom'));