SELECT ACE_ORDER
     , MASK
     , PRINCIPAL
     , SID.SID
     , CLASS
FROM IPA_ACL_OBJECT_IDENTITY OBJ
   , IPA_ACL_ENTRY ENT
   , IPA_ACL_SID SID
   , IPA_ACL_CLASS CLA
WHERE CLA.ID=OBJ.OBJECT_ID_CLASS
  AND OBJ.ID=ENT.ACL_OBJECT_IDENTITY
  AND ENT.SID=SID.ID
  AND OBJ.OBJECT_ID_IDENTITY IN (3102, 3101, 3108);