SELECT EXPPET.ID, EXPPET.IDENTIFICADOR, EXPPET.CLAU_ACCES, EXPPET.EXPEDIENT_ID, EXPPET.METAEXPEDIENT_ID, EXPPET.GRUP_ID
     , REG.ID, REG.PROCEDIMENT_CODI, REG.IDENTIFICADOR, REG.ENTITAT_ID, REG.ENTITAT_CODI
  FROM IPA_expedient_peticio EXPPET
     , IPA_REGISTRE REG
     , IPA_METAEXPEDIENT MET
WHERE EXPPET.registre_id=REG.id
  AND EXPPET.METAEXPEDIENT_ID=MET.ID
  AND REG.ENTITAT_CODI='A04003003'
  AND (EXPPET.METAEXPEDIENT_ID IN (861) AND (MET.GESTIO_AMB_GRUPS_ACTIVA=0 OR EXPPET.GRUP_ID IN (8281)));