SELECT EXPPET.ID, EXPPET.IDENTIFICADOR, EXPPET.CLAU_ACCES, EXPPET.EXPEDIENT_ID, EXPPET.METAEXPEDIENT_ID, EXPPET.GRUP_ID
     , REG.ID, REG.PROCEDIMENT_CODI, REG.IDENTIFICADOR, REG.ENTITAT_ID, REG.ENTITAT_CODI
  FROM IPA_expedient_peticio EXPPET
     , IPA_REGISTRE REG
     , IPA_METAEXPEDIENT MET
WHERE EXPPET.registre_id=REG.id
  AND EXPPET.METAEXPEDIENT_ID=MET.ID
  AND REG.ENTITAT_CODI='A04003003'
  AND (EXPPET.METAEXPEDIENT_ID IN (861) AND (MET.GESTIO_AMB_GRUPS_ACTIVA=0 OR EXPPET.GRUP_ID IN (8281)));
  
-- ANOTACIONS amb els seus enviaments ordenats els mes recents primer.
  
SELECT 
DE.ID, DE.ASSUMPTE, DE.NOT_TIPUS, DE.NOT_ENV_REF, DE.NOT_ENV_ID, DE.EXPEDIENT_ID,
DI.ID, DI.INTERESSAT_ID, DI.NOT_ENV_REF
FROM IPA_DOCUMENT_ENVIAMENT DE
, IPA_DOCUMENT_ENVIAMENT_INTER DI
WHERE DE.DTYPE='DocumentNotificacioEntity'
AND DI.DOCUMENT_ENVIAMENT_ID=DE.ID
ORDER BY DE.ID DESC;