SELECT
CONE.ID EXPEDIENT_ID,
CONE.NOM EXPEDIENT_NOM,
EXPD.ANIO EXPEDIENT_ANY,
EXPD.SEQUENCIA EXPEDIENT_SEQ,
COND.ID DOCUMENT_ID,
COND.NOM DOCUMENT_NOM,
DOC.ESTAT DOCUMENT_ESTAT,
MND.ID METADOCUMENT_ID,
MND.NOM METADOCUMENT_NOM,
MNE.ID METAEXPEDIENT_ID,
MNE.NOM METAEXPEDIENT_NOM
FROM
IPA_CONTINGUT COND,
IPA_DOCUMENT DOC,
IPA_CONTINGUT CONE,
IPA_EXPEDIENT EXPD,
IPA_NODE NOD,
IPA_METANODE MND,
IPA_METADOCUMENT MDC,
IPA_METAEXPEDIENT MEX,
IPA_METANODE MNE
WHERE
COND.TIPUS = 2
AND COND.ID = DOC.ID
AND CONE.ID = COND.EXPEDIENT_ID
AND CONE.TIPUS = 0
AND CONE.ID = EXPD.ID
AND NOD.ID = COND.ID
AND MND.ID = NOD.METANODE_ID
AND MDC.ID = NOD.METANODE_ID
AND MEX.ID = MDC.META_EXPEDIENT_ID
AND MNE.ID = MDC.META_EXPEDIENT_ID
AND MNE.ID = 2
ORDER BY
CONE.ID;