SELECT DOC_ORI.ID
     , CONT.NOM
     , DOC_ORI.ARXIU_ESTAT
     , CONT.ESBORRAT
     , DOCENV.ID
     , DOCENV.ESTAT
     , DOCENV.PF_PORTAFIRMES_ID
     , DOC_ANN.ID
     , CONT_ANN.NOM
     , DOC_ANN.ARXIU_ESTAT
     , CONT_ANN.ESBORRAT
FROM IPA_DOCUMENT_ENVIAMENT DOCENV
   , IPA_DOCUMENT DOC_ORI
   , IPA_CONTINGUT CONT
   , IPA_DOCUMENT_ENVIAMENT_DOC ANN
   , IPA_DOCUMENT DOC_ANN
   , IPA_CONTINGUT CONT_ANN
WHERE DOCENV.DOCUMENT_ID=DOC_ORI.ID
  AND DOC_ORI.ID=CONT.ID
  AND ANN.DOCUMENT_ENVIAMENT_ID=DOCENV.ID
  AND ANN.DOCUMENT_ID=DOC_ANN.ID
  AND CONT_ANN.ID=DOC_ANN.ID
  AND DOCENV.EXPEDIENT_ID=20101;