SELECT MEOGP.ID
    ,  MEOGP.EXPEDIENT_ID
    ,  META.CODI
    ,  OG.CODI
    ,  OG.NOM
FROM  IPA_EXPEDIENT EXP
    , IPA_CONTINGUT CONT
    , IPA_EXPEDIENT_ORGANPARE MEOGP
    , IPA_METAEXP_ORGAN MEXOR
    , IPA_METAEXPEDIENT META
    , IPA_ORGAN_GESTOR OG
WHERE EXP.ID=CONT.ID
  AND EXP.ID=MEOGP.EXPEDIENT_ID
  AND MEOGP.META_EXPEDIENT_ORGAN_ID=MEXOR.ID
  AND MEXOR.META_EXPEDIENT_ID=META.ID
  AND MEXOR.ORGAN_GESTOR_ID=OG.ID
  AND CONT.ESBORRAT=0
  AND CONT.ENTITAT_ID=1
ORDER BY MEOGP.EXPEDIENT_ID ASC;