SELECT DISTINCT EXP.ID
FROM  IPA_EXPEDIENT EXP
    , IPA_CONTINGUT CONT
    , IPA_EXPEDIENT_ORGANPARE MEOGP
    , IPA_METAEXP_ORGAN MEXOR
    , IPA_METAEXPEDIENT META
    , IPA_ORGAN_GESTOR OG
WHERE EXP.ID=CONT.ID
  AND EXP.ID=MEOGP.EXPEDIENT_ID
  AND MEOGP.META_EXPEDIENT_ORGAN_ID=MEXOR.ID
  AND MEXOR.META_EXPEDIENT_ID=META.ID
  AND MEXOR.ORGAN_GESTOR_ID=OG.ID
  AND CONT.ESBORRAT=0
  AND CONT.ENTITAT_ID=1
  AND EXP.ESTAT=0
  AND ( 
        (META.ID in (21261, 861)) 
         OR (MEXOR.ORGAN_GESTOR_ID in (74) and META.ID in (24609) )
    )
  and (META.PERMIS_DIRECTE=0 OR META.ID in (21261, 861))
  and (EXP.GRUP_ID is null or EXP.GRUP_ID in (8281))
  ;