SELECT MN.ID, MN.CODI, MN.ACTIU, ME.GESTIO_AMB_GRUPS_ACTIVA, ME.PERMIS_DIRECTE, OG.ID, OG.CODI, OG.NOM
FROM IPA_METAEXPEDIENT ME
, IPA_ORGAN_GESTOR OG
, IPA_METANODE MN
WHERE MN.ID=ME.ID
AND ME.ORGAN_GESTOR_ID=OG.ID(+)
AND MN.ENTITAT_ID=1;

--UPDATE IPA_EXPEDIENT EXP SET EXP.ORGAN_GESTOR_ID=74 WHERE ID IN (10345, 15521,16701, 2721, 14802, 15290, 2441, 2581, 2681, 2741, 10370, 8081);

SELECT EXP.ID, EXP.CODI, EXP.ORGAN_GESTOR_ID as OG_EXP, MN.ID, MN.CODI, MN.ACTIU, ME.GESTIO_AMB_GRUPS_ACTIVA, ME.PERMIS_DIRECTE, OG2.ID as OG_PROC, OG2.CODI, OG2.NOM
FROM IPA_EXPEDIENT EXP
, IPA_ORGAN_GESTOR OG
, IPA_NODE NOD
, IPA_CONTINGUT CON
, IPA_METANODE MN
, IPA_METAEXPEDIENT ME
, IPA_ORGAN_GESTOR OG2
WHERE EXP.ORGAN_GESTOR_ID=OG.ID(+)
AND EXP.ID=NOD.ID AND NOD.ID=CON.ID AND NOD.METANODE_ID=MN.ID AND MN.ID=ME.ID AND ME.ORGAN_GESTOR_ID=OG2.ID(+)
AND CON.ENTITAT_ID=1 AND CON.ESBORRAT = 0;-- AND EXP.ORGAN_GESTOR_ID<>OG2.ID;