SELECT EXP_TASCA.ID
, EXP_TASCA.EXPEDIENT_ID
, EXP_TASCA.METAEXP_TASCA_ID
, EXP_TASCA.TITOL
, EXP_TASCA.ESTAT
, EXP_TASCA.RESPONSABLE_ACTUAL_CODI
FROM IPA_expedient_tasca EXP_TASCA
   , IPA_EXPEDIENT EXP
   , IPA_CONTINGUT CONT
WHERE EXP_TASCA.EXPEDIENT_ID=EXP.ID
  AND EXP.ID=CONT.ID
  AND EXP_TASCA.ESTAT IN ('PENDENT', 'INICIADA', 'FINALITZADA', 'CANCELLADA', 'REBUTJADA', 'AGAFADA')
  AND CONT.ESBORRAT = 0
  AND (
        'rip_user' IN (SELECT TASCA_RESP.RESPONSABLE_CODI FROM IPA_EXPEDIENT_TASCA_RESP TASCA_RESP WHERE TASCA_RESP.TASCA_ID=EXP_TASCA.ID) OR
        'rip_user' IN (SELECT TASCA_OBSV.OBSERVADOR_CODI FROM IPA_expedient_tasca_obse TASCA_OBSV WHERE TASCA_OBSV.TASCA_ID=EXP_TASCA.ID) OR
        'rip_user' = EXP_TASCA.DELEGAT
    );