CREATE TABLE IPA_DOMINI
(
  ID                   NUMBER(19)           NOT NULL,
  CODI                 VARCHAR2(64)			NOT NULL,
  NOM                  VARCHAR2(256)	    NOT NULL,
  DESCRIPCIO           VARCHAR2(256),
  CONSULTA             VARCHAR2(256)        NOT NULL,
  CADENA               VARCHAR2(256)        NOT NULL,
  USUARI               VARCHAR2(256)        NOT NULL,
  CONTRASENYA          VARCHAR2(256)        NOT NULL,
  ENTITAT_ID           NUMBER(19)           NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64)
);


ALTER TABLE IPA_DOMINI ADD (
  CONSTRAINT IPA_DOMINI_PK PRIMARY KEY (ID));

ALTER TABLE IPA_DOMINI ADD (
  CONSTRAINT IPA_ENTITAT_DOMINI_Fk FOREIGN KEY (ENTITAT_ID) 
    REFERENCES IPA_ENTITAT (ID));