-- #725
ALTER TABLE IPA_REGISTRE_ANNEX MODIFY FIRMA_TIPUS VARCHAR2(10);
ALTER TABLE IPA_REGISTRE_ANNEX MODIFY FIRMA_PERFIL VARCHAR2(20);

-- #739 Moure justificant de zona provisional a expedient (Distribució)
ALTER TABLE IPA_REGISTRE ADD JUSTIFICANT_ARXIU_UUID VARCHAR2(256 CHAR);