-- #651
UPDATE IPA_EXPEDIENT EXP SET (EXP.ORGAN_GESTOR_ID) = (SELECT MEX.ORGAN_GESTOR_ID FROM IPA_METAEXPEDIENT MEX WHERE MEX.ID = EXP.METAEXPEDIENT_ID);
UPDATE IPA_EXPEDIENT EXP SET (EXP.ORGAN_GESTOR_ID) = (SELECT OGE.ID FROM IPA_CONTINGUT CNT, IPA_ENTITAT ENT, IPA_ORGAN_GESTOR OGE WHERE EXP.ID = CNT.ID AND ENT.ID = CNT.ENTITAT_ID AND OGE.ENTITAT_ID = ENT.ID AND OGE.CODI = ENT.UNITAT_ARREL) WHERE EXP.ORGAN_GESTOR_ID IS NULL;

-- #711
-- Executar en cas de tenir metadades de tipus domini creades
UPDATE IPA_METADADA SET MULTIPLICITAT = 1 WHERE TIPUS = 6;

-- #732
-- Esborra les carpetes que hi ha creades per defecte a nivell de tipus d'expedient
DELETE FROM IPA_METAEXPEDIENT_CARPETA;