-- #745 Canvis/millores en integració amb viafirma (PUNT2)
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_VALIDATE_CODE_ENABLED BOOLEAN;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_VALIDATE_CODE CHARACTER VARYING(100);