-- #745 Canvis/millores en integració amb viafirma (PUNT2)
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_VALIDATE_CODE_ENABLED NUMBER(1);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_VALIDATE_CODE VARCHAR2(100 CHAR);