ALTER TABLE IPA_USUARI
ADD (
    EMAILS_AGRUPATS BOOLEAN DEFAULT TRUE
);


CREATE TABLE IPA_EMAIL_PENDENT_ENVIAR
(
    ID BIGSERIAL NOT NULL,
    REMITENT CHARACTER VARYING(64) NOT NULL,
    DESTINATARI CHARACTER VARYING(64) NOT NULL,
    SUBJECT CHARACTER VARYING(1024) NOT NULL,
    TEXT CHARACTER VARYING(4000) NOT NULL,
    EVENT_TIPUS_ENUM VARCHAR2(64) NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE
);
ALTER TABLE IPA_EMAIL_PENDENT_ENVIAR ADD CONSTRAINT IPA_EMAIL_PENDENT_ENVIAR_PK PRIMARY KEY (ID);
