ALTER TABLE IPA_USUARI
ADD (
    EMAILS_AGRUPATS NUMBER(1) DEFAULT 1
);


CREATE TABLE IPA_EMAIL_PENDENT_ENVIAR
(
    ID NUMBER(19) NOT NULL,
    REMITENT VARCHAR2(64) NOT NULL,
    DESTINATARI VARCHAR2(64) NOT NULL,
    SUBJECT VARCHAR2(1024) NOT NULL,
    TEXT VARCHAR2(4000) NOT NULL,
    EVENT_TIPUS_ENUM VARCHAR2(64) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6)
);
ALTER TABLE IPA_EMAIL_PENDENT_ENVIAR ADD CONSTRAINT IPA_EMAIL_PENDENT_ENVIAR_PK PRIMARY KEY (ID);
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_EMAIL_PENDENT_ENVIARTO WWW_RIPEA;