CREATE TABLE IPA_ORGAN_GESTOR
(
	ID				NUMBER(19)		NOT NULL,
	CODI			VARCHAR2(64)	NOT NULL,
	NOM				VARCHAR2(1000)	NOT NULL,
  	ENTITAT_ID		NUMBER(19)		NOT NULL,
  	PARE_ID 		NUMBER(19)
  	CREATEDBY_CODI 	VARCHAR2(64),
  	ACTIU 			NUMBER(1,0) 	DEFAULT 1 NOT NULL
    CREATEDDATE 	TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE 	TIMESTAMP(6),
  	CONSTRAINT IPA_ORGAN_GESTOR_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_ENTITAT_ORGAN_GESTOR_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID)
);

ALTER TABLE IPA_ORGAN_GESTOR ADD CONSTRAINT IPA_ORGAN_GESTOR_UK UNIQUE (CODI, ENTITAT_ID)

ALTER TABLE IPA_METAEXPEDIENT
ADD (
    ORGAN_GESTOR_ID NUMBER(19),
    CONSTRAINT IPA_ORGAN_GESTOR_METAEXP_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES IPA_ORGAN_GESTOR (ID)
);  

