CREATE TABLE IPA_ORGAN_GESTOR
(
	ID			BIGSERIAL				NOT NULL,
	CODI		CHARACTER VARYING(64)	NOT NULL,
	NOM			CHARACTER VARYING(1000)	NOT NULL,
  	ENTITAT_ID	BIGINT					NOT NULL,
  	PARE_ID 	BIGINT,
  	ACTIU 		boolean DEFAULT '1' NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE,
    
  	CONSTRAINT IPA_ORGAN_GESTOR_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_ENTITAT_ORGAN_GESTOR_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID)
);

ALTER TABLE IPA_ORGAN_GESTOR ADD CONSTRAINT IPA_ORGAN_GESTOR_UK UNIQUE (CODI, ENTITAT_ID)

ALTER TABLE IPA_METAEXPEDIENT
ADD (
    ORGAN_GESTOR_ID BIGINT,
    CONSTRAINT IPA_ORGAN_GESTOR_METAEXP_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES IPA_ORGAN_GESTOR (ID)
);  

