ALTER TABLE IPA_ORGAN_GESTOR
DROP (
	CODI_DIR3
);

ALTER TABLE IPA_ORGAN_GESTOR
ADD (
	PARE_ID NUMBER(19)
);

ALTER TABLE IPA_ORGAN_GESTOR DROP CONSTRAINT IPA_ORGAN_GESTOR_UK;
ALTER TABLE IPA_ORGAN_GESTOR ADD CONSTRAINT IPA_ORGAN_GESTOR_UK UNIQUE (CODI, ENTITAT_ID)