
CREATE TABLE IPA_GRUP
(
    ID BIGSERIAL NOT NULL,
    ROL CHARACTER VARYING(50) NOT NULL,
    DESCRIPCIO CHARACTER VARYING(512) NOT NULL,
    ENTITAT_ID BIGINT NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE
);
ALTER TABLE IPA_GRUP ADD CONSTRAINT IPA_GRUP_PK PRIMARY KEY (ID);
ALTER TABLE IPA_GRUP ADD CONSTRAINT IPA_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT(ID);

ALTER TABLE IPA_METAEXPEDIENT
ADD (
    GESTIO_AMB_GRUPS_ACTIVA BOOLEAN DEFAULT FALSE NOT NULL
);

ALTER TABLE IPA_EXPEDIENT
ADD (
    GRUP_ID BIGINT
);
ALTER TABLE IPA_EXPEDIENT ADD CONSTRAINT IPA_GRUP_EXPEDIENT_FK FOREIGN KEY (GRUP_ID) REFERENCES IPA_GRUP(ID);


CREATE TABLE IPA_METAEXPEDIENT_GRUP (
  METAEXPEDIENT_ID  BIGSERIAL             NOT NULL,
  GRUP_ID           BIGSERIAL             NOT NULL
);

ALTER TABLE IPA_METAEXPEDIENT_GRUP ADD CONSTRAINT IPA_METAEXPEDIENT_GRUP_PK PRIMARY KEY (METAEXPEDIENT_ID, GRUP_ID);
  
ALTER TABLE IPA_METAEXPEDIENT_GRUP ADD CONSTRAINT IPA_METAEXP_METAEXPGRUP_FK FOREIGN KEY (METAEXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT(ID);
ALTER TABLE IPA_METAEXPEDIENT_GRUP ADD CONSTRAINT IPA_GRUP_METAEXPGRUP_FK FOREIGN KEY (GRUP_ID) REFERENCES IPA_GRUP(ID);

