CREATE TABLE IPA_EXPEDIENT_SEGUIDOR
(
  EXPEDIENT_ID   NUMBER(19)                     NOT NULL,
  SEGUIDOR_CODI	 VARCHAR2(64)                   NOT NULL
);

ALTER TABLE IPA_EXPEDIENT_SEGUIDOR ADD (
  CONSTRAINT IPA_EXP_SEGUIDOR_PK PRIMARY KEY (EXPEDIENT_ID, SEGUIDOR_CODI));
 
ALTER TABLE IPA_EXPEDIENT_SEGUIDOR ADD (
  CONSTRAINT IPA_PERSONA_EXPSEGUIDOR_FK FOREIGN KEY (SEGUIDOR_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_EXPEDIENT_EXPSEGUIDOR_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES IPA_EXPEDIENT (ID));
    
CREATE INDEX IPA_PERSONA_EXPSEGUIDOR_FK_I ON IPA_EXPEDIENT_SEGUIDOR(SEGUIDOR_CODI);
CREATE INDEX IPA_EXPEDIENT_EXPSEGUIDOR_FK_I ON IPA_EXPEDIENT_SEGUIDOR(EXPEDIENT_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_EXPEDIENT_SEGUIDOR TO WWW_RIPEA;