ALTER TABLE IPA_USUARI
ADD (
    EMAILS_AGRUPATS NUMBER(1) DEFAULT 1
);

CREATE TABLE IPA_EMAIL_PENDENT_ENVIAR
(
    ID NUMBER(19) NOT NULL,
    REMITENT VARCHAR2(64) NOT NULL,
    DESTINATARI VARCHAR2(64) NOT NULL,
    SUBJECT VARCHAR2(1024) NOT NULL,
    TEXT VARCHAR2(4000) NOT NULL,
    EVENT_TIPUS_ENUM VARCHAR2(64) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6)
);

ALTER TABLE IPA_EMAIL_PENDENT_ENVIAR ADD CONSTRAINT IPA_EMAIL_PENDENT_ENVIAR_PK PRIMARY KEY (ID);
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_EMAIL_PENDENT_ENVIARTO WWW_RIPEA;

CREATE TABLE IPA_ORGAN_GESTOR
(
	ID			NUMBER(19)		NOT NULL,
	CODI		VARCHAR2(64)	NOT NULL,
	NOM			VARCHAR2(1000)	NOT NULL,
  	ENTITAT_ID	NUMBER(19)		NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6),
	PARE_ID NUMBER(19),
	ACTIU NUMBER(1,0) DEFAULT 1 NOT NULL,
  	CONSTRAINT IPA_ORGAN_GESTOR_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_ENTITAT_ORGAN_GESTOR_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID),
  	CONSTRAINT IPA_ORGAN_GESTOR_UK UNIQUE (CODI, ENTITAT_ID)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_ORGAN_GESTOR WWW_RIPEA;

ALTER TABLE IPA_METAEXPEDIENT
ADD (
    ORGAN_GESTOR_ID NUMBER(19),
    PERMET_METADOCS_GENERALS NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT IPA_ORGAN_GESTOR_METAEXP_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES IPA_ORGAN_GESTOR (ID)
);  

CREATE TABLE IPA_GRUP
(
    ID NUMBER(19) NOT NULL,
    ROL VARCHAR2(50) NOT NULL,
    DESCRIPCIO VARCHAR2(512) NOT NULL,
    ENTITAT_ID NUMBER(19) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6)
);
ALTER TABLE IPA_GRUP ADD CONSTRAINT IPA_GRUP_PK PRIMARY KEY (ID);
ALTER TABLE IPA_GRUP ADD CONSTRAINT IPA_ENTITAT_GRUP_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT(ID);
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_GRUP TO WWW_RIPEA;

ALTER TABLE IPA_METAEXPEDIENT
ADD (
    GESTIO_AMB_GRUPS_ACTIVA NUMBER(1) DEFAULT 0 NOT NULL
);

ALTER TABLE IPA_EXPEDIENT
ADD (
    GRUP_ID NUMBER(19)
);
ALTER TABLE IPA_EXPEDIENT ADD CONSTRAINT IPA_GRUP_EXPEDIENT_FK FOREIGN KEY (GRUP_ID) REFERENCES IPA_GRUP(ID);

CREATE TABLE IPA_METAEXPEDIENT_GRUP (
  METAEXPEDIENT_ID  NUMBER(19)             NOT NULL,
  GRUP_ID           NUMBER(19)             NOT NULL
);

ALTER TABLE IPA_METAEXPEDIENT_GRUP ADD (
  CONSTRAINT IPA_METAEXPEDIENT_GRUP_PK PRIMARY KEY (METAEXPEDIENT_ID, GRUP_ID));
  
ALTER TABLE IPA_METAEXPEDIENT_GRUP ADD (
  CONSTRAINT IPA_METAEXP_METAEXPGRUP_FK FOREIGN KEY (METAEXPEDIENT_ID) 
    REFERENCES IPA_METAEXPEDIENT(ID),
  CONSTRAINT IPA_GRUP_METAEXPGRUP_FK FOREIGN KEY (GRUP_ID) 
    REFERENCES IPA_GRUP(ID));

CREATE TABLE IPA_EXPEDIENT_SEGUIDOR
(
  EXPEDIENT_ID   NUMBER(19)                     NOT NULL,
  SEGUIDOR_CODI	 VARCHAR2(64)                   NOT NULL
);

ALTER TABLE IPA_EXPEDIENT_SEGUIDOR ADD (
  CONSTRAINT IPA_EXP_SEGUIDOR_PK PRIMARY KEY (EXPEDIENT_ID, SEGUIDOR_CODI));
 
ALTER TABLE IPA_EXPEDIENT_SEGUIDOR ADD (
  CONSTRAINT IPA_PERSONA_EXPSEGUIDOR_FK FOREIGN KEY (SEGUIDOR_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_EXPEDIENT_EXPSEGUIDOR_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES IPA_EXPEDIENT (ID));
    
CREATE INDEX IPA_PERSONA_EXPSEGUIDOR_FK_I ON IPA_EXPEDIENT_SEGUIDOR(SEGUIDOR_CODI);
CREATE INDEX IPA_EXPEDIENT_EXPSEGUIDOR_FK_I ON IPA_EXPEDIENT_SEGUIDOR(EXPEDIENT_ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_EXPEDIENT_SEGUIDOR TO WWW_RIPEA;


