-- Nivell de foscor del tema (0 = clar, 100 = fosc) substituint el booleà MODE_FOSC.
ALTER TABLE IPA_USUARI ADD COLUMN NIVELL_FOSC INTEGER DEFAULT 0;
UPDATE IPA_USUARI SET NIVELL_FOSC = CASE WHEN MODE_FOSC THEN 100 ELSE 0 END;
ALTER TABLE IPA_USUARI DROP COLUMN MODE_FOSC;
