ALTER TABLE IPA_USUARI DROP COLUMN NIVELL_FOSC;
ALTER TABLE IPA_USUARI DROP COLUMN COLOR_PRINCIPAL;
ALTER TABLE IPA_USUARI DROP COLUMN COLOR_SECUNDARI;

ALTER TABLE IPA_USUARI ADD COLUMN TEMA_APLICACIO VARCHAR(16);
ALTER TABLE IPA_USUARI ADD COLUMN ESTIL_MENU VARCHAR(16) default 'TEMA' not null;
