CREATE TABLE IPA_EXCEPCIO_LOG (
    ID BIGINT NOT NULL,
    DATA TIMESTAMP NOT NULL,
    TIPUS VARCHAR(512),
    OBJECT_ID VARCHAR(512),
    OBJECT_CLASS VARCHAR(512),
    URI VARCHAR(1024),
    PARAM1 VARCHAR(512),
    PARAM2 VARCHAR(512),
    MESSAGE VARCHAR(4000),
    STACKTRACE TEXT,
    ENTITAT_ID BIGINT,
    CREATEDBY_CODI VARCHAR(64),
    CREATEDDATE TIMESTAMP,
    LASTMODIFIEDBY_CODI VARCHAR(64),
    LASTMODIFIEDDATE TIMESTAMP,
    CONSTRAINT IPA_EXCEPCIO_LOG_PK PRIMARY KEY (ID)
);
