-- 937
ALTER TABLE ipa_metaexpedient ADD crear_regla_dist_estat VARCHAR(10);
ALTER TABLE ipa_metaexpedient ADD crear_regla_dist_error VARCHAR(1024);

-- 1030
ALTER TABLE ipa_carpeta ADD expedient_relacionat numeric(19);
ALTER TABLE ipa_carpeta ADD CONSTRAINT ipa_carpeta_exprel_fk FOREIGN KEY (expedient_relacionat) REFERENCES ipa_expedient (id);

-- 1039
ALTER TABLE ipa_portafirmes_block_info ADD sign_date TIMESTAMP WITHOUT TIME ZONE;

-- 1043
CREATE TABLE IPA_AVIS (ID numeric(19) NOT NULL, ASSUMPTE VARCHAR(256) NOT NULL, MISSATGE VARCHAR(2048) NOT NULL, DATA_INICI TIMESTAMP WITHOUT TIME ZONE NOT NULL, DATA_FINAL TIMESTAMP WITHOUT TIME ZONE NOT NULL, ACTIU numeric(1) NOT NULL, AVIS_NIVELL VARCHAR(10) NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT IPA_AVIS_PK PRIMARY KEY (ID));
CREATE INDEX IPA_AVIS_DATA_INICI_I ON IPA_AVIS(DATA_INICI);
CREATE INDEX IPA_AVIS_DATA_FINAL_I ON IPA_AVIS(DATA_FINAL);