ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_SIGNANT_NIF CHARACTER VARYING(17);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_SIGNANT_NOM CHARACTER VARYING(90);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_OBSERVACIONS CHARACTER VARYING(256);