ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_SIGNANT_NIF VARCHAR2(17);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_SIGNANT_NOM VARCHAR2(90);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD VF_OBSERVACIONS VARCHAR2(256);