ALTER TABLE IPA_METADOCUMENT MOVE LOB (PLANTILLA_CONTINGUT) STORE AS IPA_METADOC_PLANTILLA_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_DOCUMENT MOVE LOB (FITXER_CONTINGUT) STORE AS IPA_DOCUME_FITXER_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_INTEGRACIO_ACCIO MOVE LOB (EXCEPCIO_STACKTRACE) STORE AS IPA_INTACC_STACKTRACE_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_INTEGRACIO_ACCIO MOVE LOB (PARAMETRES) STORE AS IPA_INTACC_PARAMETRES_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_EXCEPCIO_LOG MOVE LOB (STACKTRACE) STORE AS IPA_EXCLOG_STACKTRACE_LOB (TABLESPACE RIPEA_LOB);
