-- Changeset db/changelog/changes/0.9.104/1369.yaml::1697785157435-1::limit
CREATE TABLE IPA_FLUX_FIRMA_USUARI (ID numeric(19) NOT NULL, NOM VARCHAR(80) NOT NULL, DESCRIPCIO VARCHAR(256), PORTAFIRMES_FLUXID VARCHAR(64) NOT NULL, USUARI_CODI VARCHAR(64) NOT NULL, ENTITAT_ID numeric(19) NOT NULL, CREATEDBY_CODI VARCHAR(64), CREATEDDATE TIMESTAMP WITHOUT TIME ZONE, LASTMODIFIEDBY_CODI VARCHAR(64), LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT IPA_FLUX_FIRMA_USUARI_PK PRIMARY KEY (ID));

ALTER TABLE IPA_FLUX_FIRMA_USUARI ADD CONSTRAINT IPA_FLUX_FIRMA_USUARI_USU_FK FOREIGN KEY (USUARI_CODI) REFERENCES IPA_USUARI (CODI);

ALTER TABLE IPA_FLUX_FIRMA_USUARI ADD CONSTRAINT IPA_FLUX_FIRMA_USUARI_ENT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID);