-- #867
ALTER TABLE IPA_REGISTRE_ANNEX ALTER COLUMN FIRMA_TIPUS TYPE character varying(30);
ALTER TABLE IPA_REGISTRE_ANNEX ALTER COLUMN TIPUS_MIME TYPE character varying(255);
ALTER TABLE IPA_REGISTRE_ANNEX ALTER COLUMN NOM TYPE character varying(255);