CREATE TABLE IPA_PORTAFIRMES_BLOCK
(
	ID						NUMBER(19)		NOT NULL,
	BLK_ORDER 				NUMBER(19)		NOT NULL,
	DOCUMENT_ENVIAMENT_ID	NUMBER(19)		NOT NULL,
	CREATEDBY_CODI 			VARCHAR2(64),
	CREATEDDATE 			TIMESTAMP(6),
    LASTMODIFIEDBY_CODI 	VARCHAR2(64),
    LASTMODIFIEDDATE 		TIMESTAMP(6),
    VERSION       		    NUMBER(19)      NOT NULL,
	CONSTRAINT IPA_PORTAFIRMES_BLOCK_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_SIGNBLK_DOCENVDOC_FK FOREIGN KEY (DOCUMENT_ENVIAMENT_ID) REFERENCES IPA_DOCUMENT_ENVIAMENT (ID) ON DELETE CASCADE
);

CREATE TABLE IPA_PORTAFIRMES_BLOCK_INFO
(
	ID						NUMBER(19)		NOT NULL,
	PORTAFIRMES_BLOCK_ID	NUMBER(19)		NOT NULL,
	PORTAFIRMES_SIGNER_NOM	VARCHAR2(50),
	PORTAFIRMES_SIGNER_CODI	VARCHAR2(50)	NOT NULL,
	PORTAFIRMES_SIGNER_ID	VARCHAR2(9),
	SIGNED					NUMBER(1,0)		NOT NULL,
	CREATEDBY_CODI 			VARCHAR2(64),
	CREATEDDATE 			TIMESTAMP(6),
    LASTMODIFIEDBY_CODI 	VARCHAR2(64),
    LASTMODIFIEDDATE 		TIMESTAMP(6),
    VERSION       		    NUMBER(19)      NOT NULL,
	CONSTRAINT IPA_PORTAFIRMES_BLOCK_INFO_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_SIGNINFO_SIGNBLK_FK FOREIGN KEY (PORTAFIRMES_BLOCK_ID) REFERENCES IPA_PORTAFIRMES_BLOCK (ID) ON DELETE CASCADE
);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_PORTAFIRMES_BLOCK TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_PORTAFIRMES_BLOCK_INFO TO WWW_RIPEA;
