CREATE TABLE IPA_PORTAFIRMES_BLOCK
(
	ID						BIGSERIAL					NOT NULL,
	BLK_ORDER 				BIGSERIAL					NOT NULL,
	DOCUMENT_ENVIAMENT_ID	BIGSERIAL					NOT NULL,
	CREATEDBY_CODI 			CHARACTER VARYING(64),
	CREATEDDATE 			TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI 	CHARACTER VARYING(64),
    LASTMODIFIEDDATE 		TIMESTAMP WITHOUT TIME ZONE,
    VERSION       		    BIGSERIAL     				NOT NULL,
	CONSTRAINT IPA_PORTAFIRMES_BLOCK_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_SIGNBLK_DOCENVDOC_FK FOREIGN KEY (DOCUMENT_ENVIAMENT_ID) REFERENCES IPA_DOCUMENT_ENVIAMENT (ID)
);

CREATE TABLE IPA_PORTAFIRMES_BLOCK_INFO
(
	ID						BIGSERIAL				NOT NULL,
	PORTAFIRMES_BLOCK_ID	BIGSERIAL				NOT NULL,
	PORTAFIRMES_SIGNER_NOM	CHARACTER VARYING(50),
	PORTAFIRMES_SIGNER_CODI	CHARACTER VARYING(50)	NOT NULL,
	PORTAFIRMES_SIGNER_ID	CHARACTER VARYING(9),
	SIGNED					BOOLEAN		NOT NULL,
	CREATEDBY_CODI 			CHARACTER VARYING(64),
	CREATEDDATE 			TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI 	CHARACTER VARYING(64),
    LASTMODIFIEDDATE 		TIMESTAMP WITHOUT TIME ZONE,
    VERSION       		    BIGSERIAL     	 		NOT NULL,
	CONSTRAINT IPA_PORTAFIRMES_BLOCK_INFO_PK PRIMARY KEY (ID),
  	CONSTRAINT IPA_SIGNINFO_SIGNBLK_FK FOREIGN KEY (PORTAFIRMES_BLOCK_ID) REFERENCES IPA_PORTAFIRMES_BLOCK (ID)
);
