ALTER TABLE IPA_INTERESSAT DROP CONSTRAINT IPA_INTERESSAT_MULT_UK;

ALTER TABLE IPA_INTERESSAT DROP 
  CONSTRAINT IPA_REPRESENTANT_INTERESSAT_FK;
    
DELETE FROM IPA_INTERESSAT
WHERE id not in
	(SELECT MIN(id)
	FROM IPA_INTERESSAT
	GROUP BY EXPEDIENT_ID, DOCUMENT_NUM);

ALTER TABLE IPA_INTERESSAT ADD 
  CONSTRAINT IPA_REPRESENTANT_INTERESSAT_FK FOREIGN KEY (REPRESENTANT_ID) 
    REFERENCES IPA_INTERESSAT (ID);
    
ALTER TABLE ONLY IPA_INTERESSAT ADD CONSTRAINT IPA_INTERESSAT_MULT_UK UNIQUE (EXPEDIENT_ID, DOCUMENT_NUM);