--1793 Afegir nova funcionalitat per moure tot entre expedients
ALTER TABLE IPA_EXECUCIO_MASSIVA ADD EXP_ORIGEN_ID NUMBER(19,0);
ALTER TABLE IPA_EXECUCIO_MASSIVA ADD EXP_DESTI_ID NUMBER(19,0);

ALTER TABLE IPA_MASSIVA_CONTINGUT MODIFY ELEMENT_TIPUS VARCHAR2(32);