--Ampliar INTERESSAT_DOC_NUM per encabir el número de document complet (origen IPA_INTERESSAT.DOCUMENT_NUM VARCHAR(36))
ALTER TABLE IPA_HIST_EXP_INTERESSAT MODIFY (INTERESSAT_DOC_NUM VARCHAR2(36 CHAR));
