UPDATE IPA_USUARI SET IDIOMA=lower(IDIOMA);
INSERT INTO IPA_CONFIG_TYPE (CODE, VALUE) VALUES ('IDIOMES', 'ca,es');
UPDATE IPA_CONFIG SET VALUE='ca', TYPE_CODE='IDIOMES' WHERE KEY='es.caib.ripea.usuari.idioma.defecte';