INSERT INTO IPA_CONFIG_TYPE (CODE, VALUE) VALUES ('INTERFACES', 'REACT,JSP');
INSERT INTO IPA_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE,CONFIGURABLE_ORGAN,ORGAN_CODI,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,ENTITAT_CODI,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) 
values ('es.caib.ripea.interface.default','JSP','Interface per defecte al entrar a l''aplicació','GENERAL','6','0','INT',null,null,'0',null,'0','0',null,'0','0');
UPDATE IPA_USUARI SET INTERFICIE_USUARI=NULL;