CREATE TABLE IPA_EXCEPCIO_LOG (
    ID NUMBER(19,0) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    TIPUS VARCHAR2(512 CHAR),
    OBJECT_ID VARCHAR2(512 CHAR),
    OBJECT_CLASS VARCHAR2(512 CHAR),
    URI VARCHAR2(1024 CHAR),
    PARAM1 VARCHAR2(512 CHAR),
    PARAM2 VARCHAR2(512 CHAR),
    MESSAGE VARCHAR2(4000 CHAR),
    STACKTRACE CLOB,
    ENTITAT_ID NUMBER(19,0),
    CREATEDBY_CODI VARCHAR2(64 CHAR),
    CREATEDDATE TIMESTAMP,
    LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE TIMESTAMP,
    CONSTRAINT IPA_EXCEPCIO_LOG_PK PRIMARY KEY (ID)
);
