ALTER TABLE IPA_METADOCUMENT SET TABLESPACE RIPEA_LOB;
ALTER TABLE IPA_DOCUMENT SET TABLESPACE RIPEA_LOB;
ALTER TABLE IPA_INTEGRACIO_ACCIO SET TABLESPACE RIPEA_LOB;
ALTER TABLE IPA_EXCEPCIO_LOG SET TABLESPACE RIPEA_LOB;