ALTER TABLE IPA_CONT_LOG DROP CONSTRAINT IPA_CONTINGUT_CONTLOG_FK;

ALTER TABLE IPA_CONT_MOV DROP CONSTRAINT IPA_ORIGEN_CONTMOV_FK;
ALTER TABLE IPA_CONT_MOV DROP CONSTRAINT IPA_DESTI_CONTMOV_FK;
ALTER TABLE IPA_CONT_MOV DROP CONSTRAINT IPA_CONTINGUT_CONTMOV_FK;



