ALTER TABLE IPA_METAEXPEDIENT ALTER COLUMN clasif_sia TYPE character varying(30);
ALTER TABLE IPA_EXPEDIENT ALTER COLUMN NTI_CLASIF_SIA TYPE character varying(30);


CREATE TABLE IPA_EXP_COMMENT
(
  ID                   BIGINT         NOT NULL,
  EXPEDIENT_ID         BIGINT 		  NOT NULL,
  TEXT				   character varying (1024),
  CREATEDDATE          timestamp without time zone,
  LASTMODIFIEDDATE     timestamp without time zone,
  CREATEDBY_CODI       character varying(64),
  LASTMODIFIEDBY_CODI  character varying(64)
);
  
ALTER TABLE ONLY IPA_EXP_COMMENT ADD CONSTRAINT IPA_EXP_COMMENT_PK PRIMARY KEY (ID);
  
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT IPA_EXP_EXPCOMMENT_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT (ID);
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT IPA_USUCRE_EXPCOMMENT_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES IPA_USUARI (CODI);
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT DIS_USUMOD_EXPCOMMENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES IPA_USUARI (CODI);
  

