ALTER TABLE IPA_METAEXPEDIENT ALTER COLUMN clasif_sia TYPE character varying(30);
ALTER TABLE IPA_EXPEDIENT ALTER COLUMN NTI_CLASIF_SIA TYPE character varying(30);


CREATE TABLE IPA_EXP_COMMENT
(
  ID                   BIGINT         NOT NULL,
  EXPEDIENT_ID         BIGINT 		  NOT NULL,
  TEXT				   character varying (1024),
  CREATEDDATE          timestamp without time zone,
  LASTMODIFIEDDATE     timestamp without time zone,
  CREATEDBY_CODI       character varying(64),
  LASTMODIFIEDBY_CODI  character varying(64)
);
  
ALTER TABLE ONLY IPA_EXP_COMMENT ADD CONSTRAINT IPA_EXP_COMMENT_PK PRIMARY KEY (ID);
  
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT IPA_EXP_EXPCOMMENT_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT (ID);
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT IPA_USUCRE_EXPCOMMENT_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES IPA_USUARI (CODI);
ALTER TABLE IPA_EXP_COMMENT ADD CONSTRAINT DIS_USUMOD_EXPCOMMENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES IPA_USUARI (CODI);
  



--#228 Estats dels expedients 
    
CREATE TABLE IPA_EXPEDIENT_ESTAT
(
	ID                  BIGINT               			NOT NULL,
	CODI 			    character varying(256)						NOT NULL,
	NOM 			    character varying(256)						NOT NULL,
	ORDRE 			    BIGINT							NOT NULL,
	COLOR 			    character varying(256),					  
    METAEXPEDIENT_ID    BIGINT,               
    INICIAL             boolean,
    RESPONSABLE_CODI    character varying(64),
    
	
    CREATEDDATE         timestamp without time zone,
    LASTMODIFIEDDATE    timestamp without time zone,
    CREATEDBY_CODI      character varying(256),
    LASTMODIFIEDBY_CODI character varying(256)
);


ALTER TABLE IPA_EXPEDIENT ADD COLUMN EXPEDIENT_ESTAT_ID BIGINT;

ALTER TABLE IPA_EXPEDIENT_ESTAT ADD CONSTRAINT IPA_METAEXP_EXPEDIENTESTAT_FK FOREIGN KEY (METAEXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT(ID);
    
ALTER TABLE IPA_EXPEDIENT_ESTAT ADD CONSTRAINT IPA_EXPEDIENT_ESTAT_PK PRIMARY KEY (ID);

ALTER TABLE IPA_EXPEDIENT ADD CONSTRAINT IPA_EXPESTAT_EXPEDIENT_FK FOREIGN KEY (EXPEDIENT_ESTAT_ID) REFERENCES IPA_EXPEDIENT_ESTAT(ID);

ALTER TABLE IPA_ENTITAT ADD COLUMN LOGO_IMG oid;
ALTER TABLE IPA_ENTITAT ADD COLUMN CAPSALERA_COLOR_FONS character varying(32);
ALTER TABLE IPA_ENTITAT ADD COLUMN CAPSALERA_COLOR_LLETRA character varying(32);
    

