--1793 Afegir nova funcionalitat per moure tot entre expedients
ALTER TABLE IPA_EXECUCIO_MASSIVA
    ADD COLUMN EXP_ORIGEN_ID BIGINT;

ALTER TABLE IPA_EXECUCIO_MASSIVA
    ADD COLUMN EXP_DESTI_ID BIGINT;

ALTER TABLE IPA_MASSIVA_CONTINGUT
    ALTER COLUMN ELEMENT_TIPUS TYPE VARCHAR(32);