--1807 Restricció d'accés a carpetes dins d'un expedient
ALTER TABLE IPA_CARPETA
    ADD COLUMN RESTRINGIDA SMALLINT DEFAULT 0 NOT NULL;

ALTER TABLE IPA_CARPETA
    ADD COLUMN MOTIU_RESTRICCIO VARCHAR(255);

ALTER TABLE IPA_CARPETA
    ADD COLUMN RESPONSABLE_RESTRICCIO_CODI VARCHAR(64);

ALTER TABLE IPA_CARPETA
    ADD CONSTRAINT IPA_CARPETA_RESREST_FK
        FOREIGN KEY (RESPONSABLE_RESTRICCIO_CODI)
        REFERENCES IPA_USUARI (CODI);
        
        CREATE TABLE IPA_CARPETA_USUARI_REL (
    CARPETA_ID   BIGINT NOT NULL,
    USUARI_CODI  VARCHAR(64) NOT NULL,
    CONSTRAINT IPA_CARPETA_USU_REL_PK
        PRIMARY KEY (CARPETA_ID, USUARI_CODI)
);
ALTER TABLE IPA_CARPETA_USUARI_REL
    ADD CONSTRAINT IPA_CARPETA_REL_CRP_FK
        FOREIGN KEY (CARPETA_ID)
        REFERENCES IPA_CARPETA (ID);

ALTER TABLE IPA_CARPETA_USUARI_REL
    ADD CONSTRAINT IPA_CARPETA_REL_USU_FK
        FOREIGN KEY (USUARI_CODI)
        REFERENCES IPA_USUARI (CODI);