CREATE TABLE IPA_EXPEDIENT_ESTAT
(
	ID                  NUMBER(19)               			NOT NULL,
	CODI 			    VARCHAR2(256)						NOT NULL,
	NOM 			    VARCHAR2(256)						NOT NULL,
	ORDRE 			    NUMBER(10)							NOT NULL,
	COLOR 			    VARCHAR2(256),					  
    METAEXPEDIENT_ID    NUMBER(19),               
    INICIAL             NUMBER(1),
    RESPONSABLE_CODI    VARCHAR2(64),
    
	
    CREATEDDATE         TIMESTAMP(6),
    LASTMODIFIEDDATE    TIMESTAMP(6),
    CREATEDBY_CODI      VARCHAR2(256),
    LASTMODIFIEDBY_CODI VARCHAR2(256)
);


ALTER TABLE IPA_EXPEDIENT ADD EXPEDIENT_ESTAT_ID NUMBER(19);

ALTER TABLE IPA_EXPEDIENT_ESTAT ADD (
  CONSTRAINT IPA_METAEXP_EXPEDIENTESTAT_FK FOREIGN KEY (METAEXPEDIENT_ID) 
    REFERENCES IPA_METAEXPEDIENT(ID));
    
ALTER TABLE IPA_EXPEDIENT_ESTAT ADD (
  CONSTRAINT IPA_EXPEDIENT_ESTAT_PK PRIMARY KEY (ID));

ALTER TABLE IPA_EXPEDIENT ADD (
  CONSTRAINT IPA_EXPESTAT_EXPEDIENT_FK FOREIGN KEY (EXPEDIENT_ESTAT_ID) 
    REFERENCES IPA_EXPEDIENT_ESTAT(ID));