-- 1502
UPDATE IPA_METANODE SET NOM=TRIM(NOM);

-- 1068
UPDATE ipa_expedient_tasca SET DURACIO = CASE 
WHEN (DATA_LIMIT IS NULL OR DATA_INICI IS NULL) THEN NULL 
WHEN DATA_LIMIT < DATA_INICI THEN NULL
ELSE CEIL(EXTRACT(DAY FROM (DATA_LIMIT - DATA_INICI)) + 1) END;

UPDATE IPA_METAEXP_TASCA SET DURACIO = CASE 
WHEN (DATA_LIMIT IS NULL OR CREATEDDATE IS NULL) THEN NULL 
WHEN DATA_LIMIT < CREATEDDATE THEN NULL
ELSE CEIL(EXTRACT(DAY FROM (DATA_LIMIT - CREATEDDATE)) + 1) END;