
package es.caib.ripea.plugin.caib.zonaper;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackofficeFacade", targetNamespace = "urn:es:caib:zonaper:ws:v2:services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackofficeFacade {


    /**
     * 
     * @param expediente
     * @return
     *     returns java.lang.String
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "altaExpedienteReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "altaExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaExpediente")
    @ResponseWrapper(localName = "altaExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaExpedienteResponse")
    public String altaExpediente(
        @WebParam(name = "expediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        Expediente expediente)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param claveExpediente
     * @param unidadAdministrativa
     * @param identificadorExpediente
     * @param evento
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "altaEventoExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaEventoExpediente")
    @ResponseWrapper(localName = "altaEventoExpedienteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaEventoExpedienteResponse")
    public void altaEventoExpediente(
        @WebParam(name = "unidadAdministrativa", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        long unidadAdministrativa,
        @WebParam(name = "identificadorExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String identificadorExpediente,
        @WebParam(name = "claveExpediente", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String claveExpediente,
        @WebParam(name = "evento", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        EventoExpediente evento)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param nifUsuario
     * @return
     *     returns boolean
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "existeZonaPersonalUsuarioReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "existeZonaPersonalUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.ExisteZonaPersonalUsuario")
    @ResponseWrapper(localName = "existeZonaPersonalUsuarioResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.ExisteZonaPersonalUsuarioResponse")
    public boolean existeZonaPersonalUsuario(
        @WebParam(name = "nifUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String nifUsuario)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param apellido2
     * @param nombre
     * @param nif
     * @param apellido1
     * @return
     *     returns java.lang.String
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "altaZonaPersonalUsuarioReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "altaZonaPersonalUsuario", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaZonaPersonalUsuario")
    @ResponseWrapper(localName = "altaZonaPersonalUsuarioResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.AltaZonaPersonalUsuarioResponse")
    public String altaZonaPersonalUsuario(
        @WebParam(name = "nif", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String nif,
        @WebParam(name = "nombre", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String nombre,
        @WebParam(name = "apellido1", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String apellido1,
        @WebParam(name = "apellido2", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String apellido2)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param identificadorPersistenciaTramite
     * @return
     *     returns es.caib.ripea.plugin.caib.zonaper.EstadoPagos
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerEstadoPagosTramiteReturn", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerEstadoPagosTramite", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.ObtenerEstadoPagosTramite")
    @ResponseWrapper(localName = "obtenerEstadoPagosTramiteResponse", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.zonaper.ObtenerEstadoPagosTramiteResponse")
    public EstadoPagos obtenerEstadoPagosTramite(
        @WebParam(name = "identificadorPersistenciaTramite", targetNamespace = "urn:es:caib:zonaper:ws:v2:model:BackofficeFacade")
        String identificadorPersistenciaTramite)
        throws BackofficeFacadeException_Exception
    ;

}
