<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.ripea</groupId>
		<artifactId>ripea</artifactId>
		<version>1.0.4</version>
	</parent>
	<artifactId>ripea-ear</artifactId>
	<packaging>ear</packaging>
	<properties>
		<docker.image.name>${project.parent.artifactId}</docker.image.name>
		<docker.image.from>${env.DOCKER_IMAGE_FROM}</docker.image.from>
		<docker.auth.username>${env.DOCKER_USER}</docker.auth.username>
       	<docker.auth.password>${env.DOCKER_PASSWORD}</docker.auth.password>
	</properties>
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>ripea-back</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>ripea-api-interna</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>ripea-ejb</artifactId>
			<version>${project.version}</version>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>org.reactivestreams</groupId>
			<artifactId>reactive-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>ripea-backend</artifactId>
			<version>${project.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-el</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.42.1</version>
				<configuration>
					<verbose>true</verbose>
	                <authConfig>
	                   <username>${docker.auth.username}</username>
	                   <password>${docker.auth.password}</password>
	                </authConfig>
					<images>
						<image>
							<name>280421/${docker.image.name}</name>
							<alias>280421/${project.parent.artifactId}</alias>
							<build>
								<from>${docker.image.from}</from>
								<maintainer>limit@limit.es</maintainer>
								<args>
									<VITE_APP_VERSION>${project.version}</VITE_APP_VERSION>
								</args>
								<ports>
									<port>8080</port>
									<port>8787</port>
								</ports>
								<assemblies>
									<assembly>
										<name>copy_standalone_config</name>
										<inline>
											<files>
												<file>
													<source>src/main/docker/jboss/standalone-openshift.xml</source>
													<outputDirectory>.</outputDirectory>
													<destName>standalone-openshift.xml</destName>
													<fileMode>0644</fileMode>
												</file>
											</files>
										</inline>
										<targetDir>$JBOSS_HOME/standalone/configuration</targetDir>
									</assembly>
									<assembly>
										<name>copy_transformers</name>
										<inline>
											<fileSets>
												<fileSet>
													<directory>src/main/docker/transformers</directory>
													<outputDirectory>.</outputDirectory>
													<includes>
														<include>**/*</include>
													</includes>
													<fileMode>0644</fileMode>
													<directoryMode>0755</directoryMode>
												</fileSet>
											</fileSets>
										</inline>
										<targetDir>$JBOSS_HOME/apps/ripea</targetDir>
									</assembly>
									<assembly>
									    <name>copy_oracle_module</name>
									    <inline>
									        <fileSets>
									            <fileSet>
									                <directory>src/main/docker/oracle</directory>
									                <outputDirectory>modules/system/layers/base/com/oracle/main</outputDirectory>
									            </fileSet>
									        </fileSets>
									    </inline>
									    <targetDir>$JBOSS_HOME</targetDir>
									</assembly>
									<assembly>
										<descriptorRef>artifact</descriptorRef>
										<targetDir>$JBOSS_HOME/standalone/deployments</targetDir>
									</assembly>
								</assemblies>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
								<runCmds>
									<!-- Instal·lar adaptador de keycloak -->
									<run>curl -fL https://github.com/keycloak/keycloak/releases/download/12.0.4/keycloak-oidc-wildfly-adapter-12.0.4.tar.gz -o $JBOSS_HOME/keycloak-adapter.tar.gz</run>
									<run>tar xzf $JBOSS_HOME/keycloak-adapter.tar.gz -C $JBOSS_HOME --no-same-owner --no-same-permissions --touch</run>
									<run>rm $JBOSS_HOME/keycloak-adapter.tar.gz</run>
									<run>$JBOSS_HOME/bin/jboss-cli.sh --file=$JBOSS_HOME/bin/adapter-install-offline.cli -Djboss.server.config.file=standalone-openshift.xml</run>
									<run>rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history</run>
									<run>mkdir -p $JBOSS_HOME/standalone/configuration/standalone_xml_history/current</run>

									<!-- Donar permisos -->
									<run>mkdir -p $JBOSS_HOME/standalone/data/content</run>
									<run>mkdir -p $JBOSS_HOME/standalone/tmp</run>
									<run>mkdir -p $JBOSS_HOME/standalone/log</run>
									<run>chmod -R g=u $JBOSS_HOME/standalone/data</run>
									<run>chmod -R g=u $JBOSS_HOME/standalone/tmp</run>
									<run>chmod -R g=u $JBOSS_HOME/standalone/log</run>
									<run>chmod -R g=u $JBOSS_HOME/standalone/configuration/standalone_xml_history</run>
									<run>test ! -d $JBOSS_HOME/config || chmod -R g=u $JBOSS_HOME/config</run>

									<run>mkdir -p /opt/webapps/ripea</run>
									<run>chmod -R g=u /opt/webapps/ripea</run>
								</runCmds>
							</build>
							<run>
								<ports>
									<!-- Mapeig del port de debug -->
									<port>8787:8787</port>
								</ports>
								<env>
									<!-- Defineix les JAVA_OPTS per habilitar el debug -->
									<JAVA_OPTS>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</JAVA_OPTS>
								</env>
							</run>
						</image>
					</images>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<generateApplicationXml>true</generateApplicationXml>
					<defaultLibBundleDir>/lib</defaultLibBundleDir>
					<includeLibInApplicationXml>false</includeLibInApplicationXml>
					<version>6</version>
					<initializeInOrder>true</initializeInOrder>
					<skinnyWars>true</skinnyWars>
					<archive>
						<manifestEntries>
							<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
							<Implementation-Vendor>${implementation.vendor}</Implementation-Vendor>
							<Implementation-Version>${project.version}</Implementation-Version>
							<Implementation-SCM-Branch>${scmBranch}</Implementation-SCM-Branch>
							<Implementation-SCM-Revision>${buildNumber}</Implementation-SCM-Revision>
						</manifestEntries>
					</archive>
					<modules>
						<ejbModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>ripea-ejb</artifactId>
							<bundleFileName>ripea-ejb.jar</bundleFileName>
						</ejbModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>ripea-back</artifactId>
							<contextRoot>/ripeaback</contextRoot>
							<bundleFileName>ripea-back.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>ripea-api-interna</artifactId>
							<contextRoot>/ripeaapi/interna</contextRoot>
							<bundleFileName>ripea-api-interna.war</bundleFileName>
						</webModule>
					</modules>
				</configuration>
			</plugin>
	        <!--plugin>
	            <groupId>org.codehaus.mojo</groupId>
	            <artifactId>properties-maven-plugin</artifactId>
	            <version>1.2.1</version>
	            <executions>
	                <execution>
	                    <phase>initialize</phase>
	                    <goals>
	                        <goal>read-project-properties</goal>
	                    </goals>
	                </execution>
	            </executions>
	            <configuration>
	                <files>
	                    <file>${project.basedir}/../.env</file>
	                </files>
	            </configuration>
	        </plugin-->
		</plugins>
		<finalName>${project.parent.artifactId}</finalName>
	</build>
	<repositories>
		<repository>
			<id>github-governib-maven-repos</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>https://governib.github.io/maven/maven/</url>
		</repository>
	</repositories>
</project>
