
package es.caib.ripea.plugin.caib.regtel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "fault", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
public class BackofficeFacadeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BackofficeFacadeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BackofficeFacadeException_Exception(String message, BackofficeFacadeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BackofficeFacadeException_Exception(String message, BackofficeFacadeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.caib.ripea.plugin.caib.regtel.BackofficeFacadeException
     */
    public BackofficeFacadeException getFaultInfo() {
        return faultInfo;
    }

}
