INSERT INTO IPA_CONFIG (
  KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE,
  LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, CONFIGURABLE_ORGAN, ORGAN_CODI,
  CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, ENTITAT_CODI,
  CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS
) VALUES (
  'es.caib.ripea.encription.key', NULL,
  'Clau per encriptar i desencriptar parametres de les URLS (firma, escaneig, flux firma).',
  'GENERAL', '10', '1', 'PASSWORD', NULL, NULL, '0', NULL, '0', '0', NULL, '0', '0'
);

INSERT INTO IPA_CONFIG (
  KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE,
  LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, CONFIGURABLE_ORGAN, ORGAN_CODI,
  CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, ENTITAT_CODI,
  CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS
) VALUES (
  'es.caib.ripea.front.api.url', NULL,
  'URL de la API per la aplicació REACT',
  'GENERAL', '9', '1', 'TEXT', NULL, NULL, '0', NULL, '0', '0', NULL, '0', '0'
);

INSERT INTO IPA_CONFIG (
  KEY, VALUE, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE,
  LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, CONFIGURABLE_ORGAN, ORGAN_CODI,
  CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, ENTITAT_CODI,
  CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS
) VALUES (
  'es.caib.ripea.maxUploadSize', '52428800',
  'Maxim tamany dels fitxers dels camps fileUpload dels formularis.',
  'GENERAL', '11', '0', 'INT', NULL, NULL, '0', NULL, '0', '0', NULL, '0', '0'
);
