--1760
ALTER TABLE IPA_ENTITAT ADD COLUMN LOGO_RIPEA BYTEA;
ALTER TABLE IPA_ENTITAT ADD COLUMN LOGO_MENU BYTEA;

ALTER TABLE IPA_ENTITAT ADD COLUMN BLACK_LOGO_IMG BYTEA;
ALTER TABLE IPA_ENTITAT ADD COLUMN BLACK_LOGO_RIPEA BYTEA;
ALTER TABLE IPA_ENTITAT ADD COLUMN BLACK_LOGO_MENU BYTEA;

ALTER TABLE IPA_ENTITAT ADD COLUMN BLACK_CAPSALERA_COLOR_FONS VARCHAR2(32);
ALTER TABLE IPA_ENTITAT ADD COLUMN BLACK_CAPSALERA_COLOR_LLETRA VARCHAR2(32);