--1729
CREATE TABLE IPA_INTERESSAT_GRUP (
    ID                  BIGINT NOT NULL,
    NOM                 VARCHAR(255) NOT NULL,
    DESCRIPCIO          VARCHAR(1024),
    EXPEDIENT_ID        BIGINT NOT NULL,
    CREATEDBY_CODI      VARCHAR(64),
    CREATEDDATE         TIMESTAMP,
    LASTMODIFIEDDATE    TIMESTAMP,
    LASTMODIFIEDBY_CODI VARCHAR(64),
    CONSTRAINT IPA_INTERESSAT_GRUP_PK PRIMARY KEY (ID)
);

ALTER TABLE IPA_INTERESSAT_GRUP ADD CONSTRAINT IPA_INTERESSAT_GRUPEXPED_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT (ID);

CREATE TABLE IPA_INTERESSAT_GRUP_REL (
    GRUP_ID         BIGINT NOT NULL,
    INTERESSAT_ID   BIGINT NOT NULL,
    CONSTRAINT IPA_INTERESSAT_GRUP_REL_PK PRIMARY KEY (GRUP_ID, INTERESSAT_ID)
);

ALTER TABLE IPA_INTERESSAT_GRUP_REL
ADD CONSTRAINT IPA_INTERESSAT_GRUPREL_INTER_FK
FOREIGN KEY (INTERESSAT_ID) REFERENCES IPA_INTERESSAT (ID);

ALTER TABLE IPA_INTERESSAT_GRUP_REL
ADD CONSTRAINT IPA_INTERESSAT_GRUPREL_GRUP_FK
FOREIGN KEY (GRUP_ID) REFERENCES IPA_INTERESSAT_GRUP (ID);