--1669 Camp domicili de interessat alineats amb Notib
ALTER TABLE IPA_INTERESSAT ALTER COLUMN ADRESA TYPE VARCHAR(250);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_TIPUS VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_TIPUS_VIA VARCHAR(15);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_NUM_CASA VARCHAR(5);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_QUAL VARCHAR(3);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_PUNT_KM VARCHAR(10);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_AP_CORREUS VARCHAR(10);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_PORTAL VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_ESCALA VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_PLANTA VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_PORTA VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_BLOC VARCHAR(50);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_COMPLEMENT VARCHAR(250);
ALTER TABLE IPA_INTERESSAT ADD COLUMN ADRESSA_POBLACIO VARCHAR(255);