-- RIPEA 1.0.8
-- Els processos en segon pla que incorporen als expedients els certificats de les remeses i els justificants de registre
-- de les anotacions s'executen per lots: la propietat d'inici passa a ser un cron (per defecte, cada dia a les 21:00) i
-- una nova propietat desa el darrer element tractat, perquè l'execució següent continuï pels anteriors.
UPDATE IPA_CONFIG SET VALUE = '0 0 21 * * *', DESCRIPTION = 'Cron d''inici (segon minut hora dia mes dia_setmana) del procés que incorpora als expedients els certificats de les remeses, dels més recents als més antics. Cada execució dura com a màxim 8 hores i continua a partir del darrer enviament tractat. Buidar-la desactiva el procés i atura el que està en curs.' WHERE KEY = 'es.caib.ripea.segonpla.certificats.remeses.inici';
UPDATE IPA_CONFIG SET VALUE = '0 0 21 * * *', DESCRIPTION = 'Cron d''inici (segon minut hora dia mes dia_setmana) del procés que incorpora als expedients els justificants de registre de les anotacions acceptades, de les més recents a les més antigues. Cada execució dura com a màxim 8 hores i continua a partir de la darrera anotació tractada. Buidar-la desactiva el procés i atura el que està en curs.' WHERE KEY = 'es.caib.ripea.segonpla.justificants.registre.inici';
Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
    ('0','SCHEDULLED','es.caib.ripea.segonpla.certificats.remeses.darrerId',null,'Id del darrer enviament tractat pel procés que incorpora als expedients els certificats de les remeses. L''actualitza el procés: l''execució següent continua pels enviaments anteriors. Buidar-la per tornar a començar pels més recents.',15,'INT','0','0','0','0','0');
Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
    ('0','SCHEDULLED','es.caib.ripea.segonpla.justificants.registre.darrerId',null,'Id de la darrera anotació tractada pel procés que incorpora als expedients els justificants de registre. L''actualitza el procés: l''execució següent continua per les anotacions anteriors. Buidar-la per tornar a començar per les més recents.',16,'INT','0','0','0','0','0');
