Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
    ('0','SCHEDULLED','es.caib.ripea.sse.ping.interval','20000','Interval de temps (ms) entre pings de manteniment de les connexions SSE.',12,'INT','0','0','0','0','0');
