Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
('0','CONTINGUT','es.caib.ripea.documents.descarrega.url',NULL,'URL de descàrrega directa de documents imprimibles (s''hi afegeix el CSV)','43','TEXT','0','1','0','1','0');
