ALTER TABLE IPA_METAEXP_TASCA
ADD (
    ESTAT_CREAR_TASCA_ID BIGINT,
    ESTAT_FINALITZAR_TASCA_ID BIGINT
);
ALTER TABLE IPA_METAEXP_TASCA ADD CONSTRAINT IPA_METAEXP_TASCA_CREAR_FK FOREIGN KEY (ESTAT_CREAR_TASCA_ID) REFERENCES IPA_EXPEDIENT_ESTAT;
ALTER TABLE IPA_METAEXP_TASCA ADD CONSTRAINT IPA_METAEXP_TASCA_FINALI_FK FOREIGN KEY (ESTAT_FINALITZAR_TASCA_ID) REFERENCES IPA_EXPEDIENT_ESTAT;