ALTER TABLE IPA_METANODE DROP CONSTRAINT IPA_METANODE_MULT_UK;

ALTER TABLE IPA_METAEXPEDIENT ADD ENTITAT_ID NUMBER(19);
ALTER TABLE IPA_METAEXPEDIENT ADD CODI VARCHAR2(64 CHAR);
UPDATE IPA_METAEXPEDIENT MEX SET (ENTITAT_ID, CODI) = (SELECT MEN.ENTITAT_ID, MEN.CODI FROM IPA_METANODE MEN WHERE MEN.ID = MEX.ID);
ALTER TABLE IPA_METAEXPEDIENT MODIFY ENTITAT_ID NOT NULL;
ALTER TABLE IPA_METAEXPEDIENT MODIFY CODI NOT NULL;

ALTER TABLE IPA_METADOCUMENT ADD CODI VARCHAR2(64 CHAR);
UPDATE IPA_METADOCUMENT MED SET (CODI) = (SELECT MEN.CODI FROM IPA_METANODE MEN WHERE MEN.ID = MED.ID);
ALTER TABLE IPA_METADOCUMENT MODIFY CODI NOT NULL;

ALTER TABLE IPA_METAEXPEDIENT ADD CONSTRAINT IPA_METAEXP_ENTITAT_CODI_UK UNIQUE (ENTITAT_ID, CODI);
ALTER TABLE IPA_METADOCUMENT ADD CONSTRAINT IPA_METADOC_METAEXP_CODI_UK UNIQUE (META_EXPEDIENT_ID, CODI);