CREATE TABLE IPA_METAEXP_ORGAN
(
    ID NUMBER(19)                NOT NULL,
    META_EXPEDIENT_ID NUMBER(19) NOT NULL,
    ORGAN_GESTOR_ID  NUMBER(19)  NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6)
);
ALTER TABLE IPA_METAEXP_ORGAN ADD (
  CONSTRAINT IPA_METAEXPORG_PK PRIMARY KEY (ID));
ALTER TABLE IPA_METAEXP_ORGAN
ADD (
    CONSTRAINT IPA_METAEXP_METAEXPORG_FK FOREIGN KEY (META_EXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT (ID),
    CONSTRAINT IPA_ORGAN_METAEXPORG_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES IPA_ORGAN_GESTOR (ID)
);

ALTER TABLE IPA_EXPEDIENT
ADD (
    ORGAN_GESTOR_ID NUMBER(19),
    CONSTRAINT IPA_ORGAN_GESTOR_EXP_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES IPA_ORGAN_GESTOR (ID)
);
UPDATE IPA_EXPEDIENT EXP SET (EXP.ORGAN_GESTOR_ID) = (SELECT MEX.ORGAN_GESTOR_ID FROM IPA_METAEXPEDIENT MEX WHERE MEX.ID = EXP.METAEXPEDIENT_ID);
UPDATE IPA_EXPEDIENT EXP SET (EXP.ORGAN_GESTOR_ID) = (SELECT OGE.ID FROM IPA_CONTINGUT CNT, IPA_ENTITAT ENT, IPA_ORGAN_GESTOR OGE WHERE EXP.ID = CNT.ID AND ENT.ID = CNT.ENTITAT_ID AND OGE.ENTITAT_ID = ENT.ID AND OGE.CODI = ENT.UNITAT_ARREL) WHERE EXP.ORGAN_GESTOR_ID IS NULL;
ALTER TABLE IPA_EXPEDIENT MODIFY ORGAN_GESTOR_ID NOT NULL;