UPDATE IPA_PINBAL_SERVEI SET NOM='Consulta de dades d''identitat' WHERE CODI='SVDDGPCIWS02';
UPDATE IPA_PINBAL_SERVEI SET NOM='Verificació de dades d''identitat' WHERE CODI='SVDDGPVIWS02';
UPDATE IPA_PINBAL_SERVEI SET NOM='Estar al corrent d''obligacions tributàries per a sol·licitud de subvencions i ajudes de la CCAA' WHERE CODI='SVDCCAACPASWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de dades de discapacitat' WHERE CODI='SVDSCDDWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de padró de convivència' WHERE CODI='SCDCPAJU';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de família nombrosa' WHERE CODI='SVDSCTFNWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Estar al corrent d''obligacions tributàries per a la contractació amb la CCAA' WHERE CODI='SVDCCAACPCWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Estar al corrent de pagament amb la Seguretat Social' WHERE CODI='Q2827003ATGSS001';
UPDATE IPA_PINBAL_SERVEI SET NOM='Consulta de inexistència de delictes sexuals per dades de filiació' WHERE CODI='SVDDELSEXWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de padró històric' WHERE CODI='SCDHPAJU';
UPDATE IPA_PINBAL_SERVEI SET NOM='Consulta del nivell de renda' WHERE CODI='NIVRENTI';
UPDATE IPA_PINBAL_SERVEI SET NOM='Estar al corrent d''obligacions tributàries per a sol·licitud de subvencions i ajudes amb indicació d''incompliments' WHERE CODI='ECOT103';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de dades de residència legal d''estrangers per documentació' WHERE CODI='SVDDGPRESIDENCIALEGALDOCWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de naixement' WHERE CODI='SVDRRCCNACIMIENTOWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de matrimoni' WHERE CODI='SVDRRCCMATRIMONIOWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de defunció' WHERE CODI='SVDRRCCDEFUNCIONWS01';
UPDATE IPA_PINBAL_SERVEI SET NOM='Servei de consulta de condició de becat' WHERE CODI='SVDBECAWS01';

--Actualitzam els identificadors del servei pinbal, ja no serán els del enumerat, sino el ID de IPA_PINBAL_SERVEI
--(En el seguent script crearem la FK)
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDBECAWS01') WHERE PINBAL_SERVEI=16;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDRRCCDEFUNCIONWS01') WHERE PINBAL_SERVEI=15;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDRRCCMATRIMONIOWS01') WHERE PINBAL_SERVEI=14;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDRRCCNACIMIENTOWS01') WHERE PINBAL_SERVEI=13;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDDGPRESIDENCIALEGALDOCWS01') WHERE PINBAL_SERVEI=12;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='ECOT103') WHERE PINBAL_SERVEI=11;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='NIVRENTI') WHERE PINBAL_SERVEI=10;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SCDHPAJU') WHERE PINBAL_SERVEI=9;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDDELSEXWS01') WHERE PINBAL_SERVEI=8;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='Q2827003ATGSS001') WHERE PINBAL_SERVEI=7;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDCCAACPCWS01') WHERE PINBAL_SERVEI=6;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDSCTFNWS01') WHERE PINBAL_SERVEI=5;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SCDCPAJU') WHERE PINBAL_SERVEI=4;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDSCDDWS01') WHERE PINBAL_SERVEI=3;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDCCAACPASWS01') WHERE PINBAL_SERVEI=2;
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDDGPVIWS02') WHERE PINBAL_SERVEI=1; 
UPDATE IPA_METADOCUMENT SET PINBAL_SERVEI=(SELECT ID FROM IPA_PINBAL_SERVEI WHERE CODI='SVDDGPCIWS02') WHERE PINBAL_SERVEI=0;