CREATE TABLE IPA_METAEXP_TASCA_VALIDACIO (
ID BIGINT NOT NULL,
TASCA_ID BIGINT NOT NULL,
ITEM_TIPUS VARCHAR(8) NOT NULL,
ITEM_ID BIGINT NOT NULL,
VALIDACIO_TIPUS VARCHAR(8) NOT NULL,
ACTIVA SMALLINT DEFAULT 1,
CREATEDBY_CODI VARCHAR(64),
CREATEDDATE TIMESTAMP,
LASTMODIFIEDBY_CODI VARCHAR(64),
LASTMODIFIEDDATE TIMESTAMP
);

ALTER TABLE IPA_METAEXP_TASCA_VALIDACIO ADD CONSTRAINT IPA_METAEXP_TASCA_VALIDACIO_PK PRIMARY KEY (ID);
ALTER TABLE IPA_METAEXP_TASCA_VALIDACIO ADD CONSTRAINT IPA_METAEXP_TASCA_VALIDACIO_FK FOREIGN KEY (TASCA_ID) REFERENCES IPA_METAEXP_TASCA (ID);

-- El ITEM_ID será una FK hacia IPA_METADADA o IPA_METADOCUMENT según el valor del campo ITEM_TIPUS
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_METAEXP_TASCA_VALIDACIO TO www_ripea;