ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH NUMBER(1);
ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH_OBLIGAT NUMBER(1);

ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENTREGA_POSTAL NUMBER(1);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_INTERESSAT_ID;

CREATE TABLE IPA_DOCUMENT_ENVIAMENT_INTER
(
  ID                   	NUMBER(19) NOT NULL,
  DOCUMENT_ENVIAMENT_ID NUMBER(19) NOT NULL,
  INTERESSAT_ID 		NUMBER(19) NOT NULL,
  NOT_ENV_REF   		VARCHAR(100),
  CREATEDBY_CODI       VARCHAR2(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
);

