ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH BOOLEAN;
ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH_OBLIGAT BOOLEAN;

ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENTREGA_POSTAL BOOLEAN;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_INTERESSAT_ID;

CREATE TABLE IPA_DOCUMENT_ENVIAMENT_INTER
(
  ID                   	BIGINT NOT NULL,
  DOCUMENT_ENVIAMENT_ID BIGINT NOT NULL,
  INTERESSAT_ID 		BIGINT NOT NULL,
  NOT_ENV_REF   		CHARACTER VARYING (100),
  CREATEDDATE         timestamp without time zone,
  LASTMODIFIEDDATE    timestamp without time zone,
  CREATEDBY_CODI      character varying (256),
  LASTMODIFIEDBY_CODI character varying (256)
);



