 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_IDIOMA;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TITOL;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TEXT;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TEXTM;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_OFICI_TITOL;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_OFICI_TEXT;

 
 
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_PROC_CODI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_LIB;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_OFI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_ORG;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_EXP_UNI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TITOL;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TEXT;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TEXTM;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_OFICI_TITOL;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_OFICI_TEXT;
 
 
 
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SERVEI_TIPUS CHARACTER VARYING(10);