ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH NUMBER(1);
ALTER TABLE IPA_INTERESSAT ADD ENTREGA_DEH_OBLIGAT NUMBER(1);

ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENTREGA_POSTAL NUMBER(1);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_INTERESSAT_ID;

CREATE TABLE IPA_DOCUMENT_ENVIAMENT_INTER
(
  ID                   	NUMBER(19) NOT NULL,
  DOCUMENT_ENVIAMENT_ID NUMBER(19) NOT NULL,
  INTERESSAT_ID 		NUMBER(19) NOT NULL,
  NOT_ENV_REF   		VARCHAR(100),
  CREATEDBY_CODI       VARCHAR2(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6),
);

 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_IDIOMA;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TITOL;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TEXT;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_AVIS_TEXTM;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_OFICI_TITOL;
 ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN NOT_SEU_OFICI_TEXT;

 
 
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_PROC_CODI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_LIB;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_OFI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_REG_ORG;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_SEU_EXP_UNI;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TITOL;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TEXT;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_AVIS_TEXTM;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_OFICI_TITOL;
 ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN NOT_OFICI_TEXT;
 
 
 
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SERVEI_TIPUS VARCHAR(10);

ALTER TABLE IPA_USUARI DROP COLUMN REBRE_EMAILS;
ALTER TABLE IPA_USUARI DROP COLUMN EMAILS_AGRUPATS;

ALTER TABLE IPA_REGISTRE_INTERESSAT ADD ORGAN_CODI VARCHAR(9);