CREATE TABLE IPA_HISTORIC
(
	ID						 BIGSERIAL	    NOT NULL,
    ENTITAT_ID               BIGSERIAL     NOT NULL,
    ORGAN_ID                 BIGSERIAL,
    METAEXPEDIENT_ID         BIGSERIAL     NOT NULL,
    TIPUS                    BIGSERIAL     NOT NULL,
    DATA                     TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    N_EXPED_CREATS	         BIGSERIAL	    NOT NULL,
    N_EXPED_CREATS_ACUM      BIGSERIAL	    NOT NULL,
    N_EXPED_OBERTS	         BIGSERIAL	    NOT NULL,
    N_EXPED_OBERTS_ACUM      BIGSERIAL	    NOT NULL,
    N_EXPED_TANCATS          BIGSERIAL	    NOT NULL,
    N_EXPED_TANCATS_ACUM     BIGSERIAL	    NOT NULL,
    CREATEDBY_CODI           CHARACTER VARYING(64),
    CREATEDDATE              TIMESTAMP(6),
    LASTMODIFIEDBY_CODI      CHARACTER VARYING(64),
    LASTMODIFIEDDATE         TIMESTAMP WITHOUT TIME ZONE,
    VERSION                  BIGSERIAL      NOT NULL
);

CREATE TABLE IPA_HIST_EXPEDIENT
(
	ID						 BIGSERIAL	    NOT NULL,
	N_EXPED_AMB_ALERTES      BIGSERIAL	    NOT NULL,
	N_EXPED_ERRORS_VALID     BIGSERIAL	    NOT NULL,
	N_DOCS_PENDENTS_SIGN     BIGSERIAL     NOT NULL,
	N_DOCS_SIGN              BIGSERIAL		NOT NULL,
	N_DOCS_PENDENTS_NOTIF    BIGSERIAL		NOT NULL,
	N_DOCS_NOTIF             BIGSERIAL	    NOT NULL
);

CREATE TABLE IPA_HIST_EXP_USUARI
(
	ID						 BIGSERIAL	    NOT NULL,
  	USUARI_CODI              CHARACTER VARYING(64)   NOT NULL,
	N_TASQUES_TRAMITADES     BIGSERIAL	    NOT NULL
);

CREATE TABLE IPA_HIST_EXP_INTERESSAT
(
	ID						 BIGSERIAL					NOT NULL,
  	INTERESSAT_DOC_NUM       CHARACTER VARYING(17)		NOT NULL
);

ALTER TABLE IPA_HISTORIC ADD (
  CONSTRAINT IPA_HISTORIC_OID_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_HISTORIC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID),
  CONSTRAINT IPA_HISTORIC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES IPA_ORGAN_GESTOR (ID),
  CONSTRAINT IPA_HISTORIC_METAEXP_FK FOREIGN KEY (METAEXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT (ID)

);

ALTER TABLE IPA_HIST_EXPEDIENT ADD (
  CONSTRAINT IPA_HIST_EXPEDIENT_OID_PK PRIMARY KEY (ID)

);

ALTER TABLE IPA_HIST_EXP_USUARI ADD (
  CONSTRAINT IPA_HIST_EXP_USUARI_OID_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_HIST_EXP_USUARI_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES IPA_USUARI (CODI)
);

ALTER TABLE IPA_HIST_EXP_INTERESSAT ADD (
  CONSTRAINT IPA_HISTEXPINTERESSAT_OID_PK PRIMARY KEY (ID)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HISTORIC TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXPEDIENT TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXP_USUARI TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXP_INTERESSAT TO WWW_RIPEA;