CREATE TABLE IPA_HISTORIC
(
	ID						 NUMBER(19)	    NOT NULL,
    ENTITAT_ID               NUMBER(19)     NOT NULL,
    ORGAN_ID                 NUMBER(19),
    METAEXPEDIENT_ID         NUMBER(19)     NOT NULL,
    TIPUS                    NUMBER(10)     NOT NULL,
    DATA                     TIMESTAMP(6)   NOT NULL,
    N_EXPED_CREATS	         NUMBER(19)	    NOT NULL,
    N_EXPED_CREATS_ACUM      NUMBER(19)	    NOT NULL,
    N_EXPED_OBERTS	         NUMBER(19)	    NOT NULL,
    N_EXPED_OBERTS_ACUM      NUMBER(19)	    NOT NULL,
    N_EXPED_TANCATS          NUMBER(19)	    NOT NULL,
    N_EXPED_TANCATS_ACUM     NUMBER(19)	    NOT NULL,
    CREATEDBY_CODI           VARCHAR2(64),
    CREATEDDATE              TIMESTAMP(6),
    LASTMODIFIEDBY_CODI      VARCHAR2(64),
    LASTMODIFIEDDATE         TIMESTAMP(6),
    VERSION                  NUMBER(19)      NOT NULL
);

ALTER TABLE IPA_HISTORIC ADD (
  CONSTRAINT IPA_HISTORIC_OID_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_HISTORIC_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES IPA_ENTITAT (ID),
  CONSTRAINT IPA_HISTORIC_ORGAN_FK FOREIGN KEY (ORGAN_ID) REFERENCES IPA_ORGAN_GESTOR (ID),
  CONSTRAINT IPA_HISTORIC_METAEXP_FK FOREIGN KEY (METAEXPEDIENT_ID) REFERENCES IPA_METAEXPEDIENT (ID)

);


CREATE TABLE IPA_HIST_EXPEDIENT
(
	ID						 NUMBER(19)	    NOT NULL,
	N_EXPED_AMB_ALERTES      NUMBER(19)	    NOT NULL,
	N_EXPED_ERRORS_VALID      NUMBER(19)	    NOT NULL,
	N_DOCS_PENDENTS_SIGN     NUMBER(19)     NOT NULL,
	N_DOCS_SIGN              NUMBER(19)		NOT NULL,
	N_DOCS_PENDENTS_NOTIF    NUMBER(19)		NOT NULL,
	N_DOCS_NOTIF             NUMBER(19)	    NOT NULL
);


ALTER TABLE IPA_HIST_EXPEDIENT ADD (
  CONSTRAINT IPA_HIST_EXPEDIENT_OID_PK PRIMARY KEY (ID)
);

CREATE TABLE IPA_HIST_EXP_USUARI
(
	ID						 NUMBER(19)	    NOT NULL,
  	USUARI_CODI              VARCHAR2(64)   NOT NULL,
	N_TASQUES_TRAMITADES     NUMBER(19)	    NOT NULL
);

ALTER TABLE IPA_HIST_EXP_USUARI ADD (
  CONSTRAINT IPA_HIST_EXP_USUARI_OID_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_HIST_EXP_USUARI_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES IPA_USUARI (CODI)
);

CREATE TABLE IPA_HIST_EXP_INTERESSAT
(
	ID						 NUMBER(19)	    NOT NULL,
  	INTERESSAT_DOC_NUM       VARCHAR2(17)     NOT NULL
);

ALTER TABLE IPA_HIST_EXP_INTERESSAT ADD (
  CONSTRAINT IPA_HISTEXPINTERESSAT_OID_PK PRIMARY KEY (ID)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HISTORIC TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXPEDIENT TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXP_USUARI TO WWW_RIPEA;
GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_HIST_EXP_INTERESSAT TO WWW_RIPEA;

