CREATE TABLE IPA_METAEXP_TASCA_VALIDACIO (
ID NUMBER(38, 0) NOT NULL,
TASCA_ID NUMBER(38, 0) NOT NULL,
ITEM_TIPUS VARCHAR2(8 CHAR) NOT NULL,
ITEM_ID NUMBER(38, 0) NOT NULL,
VALIDACIO_TIPUS VARCHAR2(8 CHAR) NOT NULL,
ACTIVA NUMBER(1) DEFAULT 1,
CREATEDBY_CODI VARCHAR2(64 CHAR),
CREATEDDATE TIMESTAMP(6),
LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR),
LASTMODIFIEDDATE TIMESTAMP(6));

ALTER TABLE IPA_METAEXP_TASCA_VALIDACIO ADD CONSTRAINT IPA_METAEXP_TASCA_VALIDACIO_PK PRIMARY KEY (ID);
ALTER TABLE IPA_METAEXP_TASCA_VALIDACIO ADD CONSTRAINT IPA_METAEXP_TASCA_VALIDACIO_FK FOREIGN KEY (TASCA_ID) REFERENCES IPA_METAEXP_TASCA (id);
--EL ITEM_ID será una FK cap a IPA_METADADA o IPA_METADOCUMENT segons el valor del camp ITEM_TIPUS
grant select, update, insert, delete on IPA_METAEXP_TASCA_VALIDACIO to www_ripea;