
package es.caib.ripea.plugin.caib.regtel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackofficeFacade", targetNamespace = "urn:es:caib:regtel:ws:v2:services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackofficeFacade {


    /**
     * 
     * @param entrada
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.ResultadoRegistro
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "registroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroEntrada")
    @ResponseWrapper(localName = "registroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroEntradaResponse")
    public ResultadoRegistro registroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroEntrada entrada)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param entrada
     * @param diasPersistencia
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.ReferenciaRDSAsientoRegistral
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "prepararRegistroEntradaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "prepararRegistroEntrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.PrepararRegistroEntrada")
    @ResponseWrapper(localName = "prepararRegistroEntradaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.PrepararRegistroEntradaResponse")
    public ReferenciaRDSAsientoRegistral prepararRegistroEntrada(
        @WebParam(name = "entrada", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroEntrada entrada,
        @WebParam(name = "diasPersistencia", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String diasPersistencia)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param referenciaRDS
     * @param firma
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.ResultadoRegistro
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "registroEntradaConFirmaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroEntradaConFirma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroEntradaConFirma")
    @ResponseWrapper(localName = "registroEntradaConFirmaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroEntradaConFirmaResponse")
    public ResultadoRegistro registroEntradaConFirma(
        @WebParam(name = "referenciaRDS", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        ReferenciaRDSAsientoRegistral referenciaRDS,
        @WebParam(name = "firma", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        FirmaWS firma)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param notificacion
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.ResultadoRegistro
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "registroSalidaReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "registroSalida", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroSalida")
    @ResponseWrapper(localName = "registroSalidaResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.RegistroSalidaResponse")
    public ResultadoRegistro registroSalida(
        @WebParam(name = "notificacion", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        DatosRegistroSalida notificacion)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param numeroRegistro
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.AcuseRecibo
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.ObtenerAcuseRecibo")
    @ResponseWrapper(localName = "obtenerAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.ObtenerAcuseReciboResponse")
    public AcuseRecibo obtenerAcuseRecibo(
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String numeroRegistro)
        throws BackofficeFacadeException_Exception
    ;

    /**
     * 
     * @param numeroRegistro
     * @return
     *     returns es.caib.ripea.plugin.caib.regtel.DetalleAcuseRecibo
     * @throws BackofficeFacadeException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerDetalleAcuseReciboReturn", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerDetalleAcuseRecibo", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.ObtenerDetalleAcuseRecibo")
    @ResponseWrapper(localName = "obtenerDetalleAcuseReciboResponse", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade", className = "es.caib.ripea.plugin.caib.regtel.ObtenerDetalleAcuseReciboResponse")
    public DetalleAcuseRecibo obtenerDetalleAcuseRecibo(
        @WebParam(name = "numeroRegistro", targetNamespace = "urn:es:caib:regtel:ws:v2:model:BackofficeFacade")
        String numeroRegistro)
        throws BackofficeFacadeException_Exception
    ;

}
