/**
 * 
 */
package es.caib.ripea.core.api.dto;


public enum EventTipusEnumDto {
	AGAFAT_ALTRE_USUARI,
	CANVI_ESTAT_PORTAFIRMES,
	CANVI_ESTAT_NOTIFICACIO,
	CANVI_ESTAT_TASCA,
	CANVI_ESTAT_VIAFIRMA,
	CANVI_ESTAT_REVISIO,
	CANVI_RESPONSABLES_TASCA,
	PROCEDIMENT_COMENTARI,
	NOVA_ANOTACIO,
	ALLIBERAT,
	MODIFICACIO_DATALIMIT_TASCA,
	DELEGAT_TASCA,
	CANCELAR_DELEGACIO_TASCA,
	ENVIAR_FICHERO
}
