package es.caib.ripea.core.api.dto;


public enum HistoricEstadisticsEnumDto {
	EXPEDIENTS_CREATS,
	EXPEDIENTS_CREATS_ACUM,
	EXPEDIENTS_OBERTS,
	EXPEDIENTS_OBERTS_ACUM,
	EXPEDIENTS_TANCATS,
	EXPEDIENTS_TANCATS_ACUM,
	EXPEDIENTS_AMB_ALERTES,
	EXPEDIENTS_AMB_ERRORS_VALID,
	DOCUMENTS_PENDENTS_SIGNAR,
	DOCUMENTS_SIGNATS,
	DOCUMENTS_PENDENTS_NOTIFICAR,
	DOCUMENTS_NOTIFICATS
}
