ALTER TABLE IPA_DOCUMENT_ENVIAMENT_INTER 
	ADD COLUMN   NOT_ENV_DAT_DATA     		TIMESTAMP WITHOUT TIMEZONE,
	ADD COLUMN   NOT_ENV_DAT_ORIG     		CHARACTER VARYING(20),
	ADD COLUMN   NOT_ENV_CERT_DATA    		TIMESTAMP WITHOUT TIMEZONE,
	ADD COLUMN   NOT_ENV_CERT_ORIG    		CHARACTER VARYING(20),
	ADD COLUMN   ERROR                		BOOLEAN,
	ADD COLUMN   ERROR_DESC           		CHARACTER VARYING(2048);
	
	
ALTER TABLE IPA_DOCUMENT_ENVIAMENT
  ADD COLUMN    NOTIFICACIO_ESTAT            	CHARACTER VARYING(255);

  
ALTER TABLE IPA_INTERESSAT ADD INCAPACITAT BOOLEAN;