UPDATE IPA_METADOCUMENT SET NTI_ORIGEN='O0' WHERE NTI_ORIGEN IS NULL;
UPDATE IPA_METADOCUMENT SET NTI_TIPDOC='TD99' WHERE NTI_TIPDOC IS NULL;
ALTER TABLE IPA_METADOCUMENT MODIFY NTI_ORIGEN NOT NULL;
ALTER TABLE IPA_METADOCUMENT MODIFY NTI_TIPDOC NOT NULL;