ALTER TABLE IPA_METAEXPEDIENT MODIFY clasif_sia VARCHAR2(30);
ALTER TABLE IPA_EXPEDIENT MODIFY NTI_CLASIF_SIA VARCHAR2(30);



CREATE TABLE IPA_EXP_COMMENT
(
  ID                   NUMBER(19)         NOT NULL,
  EXPEDIENT_ID         NUMBER(19) 				NOT NULL,
  TEXT				   			 VARCHAR2 (1024),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDBY_CODI  VARCHAR2(64)
);

ALTER TABLE IPA_EXP_COMMENT ADD (
  CONSTRAINT IPA_EXP_COMMENT_PK PRIMARY KEY (ID));  
  
ALTER TABLE IPA_EXP_COMMENT ADD (
  CONSTRAINT IPA_EXP_EXPCOMMENT_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES IPA_EXPEDIENT (ID),
  CONSTRAINT IPA_USUCRE_EXPCOMMENT_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT DIS_USUMOD_EXPCOMMENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));  
