--#219-------------------------------------------------------------------------
ALTER TABLE IPA_METAEXPEDIENT MODIFY clasif_sia VARCHAR2(30);
ALTER TABLE IPA_EXPEDIENT MODIFY NTI_CLASIF_SIA VARCHAR2(30);


--#225-------------------------------------------------------------------------
CREATE TABLE IPA_EXP_COMMENT
(
  ID                   NUMBER(19)         NOT NULL,
  EXPEDIENT_ID         NUMBER(19) 				NOT NULL,
  TEXT				   VARCHAR2 (1024),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDBY_CODI  VARCHAR2(64)
);
ALTER TABLE IPA_EXP_COMMENT ADD (
  CONSTRAINT IPA_EXP_COMMENT_PK PRIMARY KEY (ID));    
ALTER TABLE IPA_EXP_COMMENT ADD (
  CONSTRAINT IPA_EXP_EXPCOMMENT_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES IPA_EXPEDIENT (ID),
  CONSTRAINT IPA_USUCRE_EXPCOMMENT_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT DIS_USUMOD_EXPCOMMENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));  
    
    
--#228-------------------------------------------------------------------------
CREATE TABLE IPA_EXPEDIENT_ESTAT
(
	ID                  NUMBER(19)               			NOT NULL,
	CODI 			    VARCHAR2(256)						NOT NULL,
	NOM 			    VARCHAR2(256)						NOT NULL,
	ORDRE 			    NUMBER(10)							NOT NULL,
	COLOR 			    VARCHAR2(256),					  
    METAEXPEDIENT_ID    NUMBER(19),               
    INICIAL             NUMBER(1),
    RESPONSABLE_CODI    VARCHAR2(64),
    
	
    CREATEDDATE         TIMESTAMP(6),
    LASTMODIFIEDDATE    TIMESTAMP(6),
    CREATEDBY_CODI      VARCHAR2(256),
    LASTMODIFIEDBY_CODI VARCHAR2(256)
);


ALTER TABLE IPA_EXPEDIENT ADD EXPEDIENT_ESTAT_ID NUMBER(19);

ALTER TABLE IPA_EXPEDIENT_ESTAT ADD (
  CONSTRAINT IPA_METAEXP_EXPEDIENTESTAT_FK FOREIGN KEY (METAEXPEDIENT_ID) 
    REFERENCES IPA_METAEXPEDIENT(ID));
    
ALTER TABLE IPA_EXPEDIENT_ESTAT ADD (
  CONSTRAINT IPA_EXPEDIENT_ESTAT_PK PRIMARY KEY (ID));

ALTER TABLE IPA_EXPEDIENT ADD (
  CONSTRAINT IPA_EXPESTAT_EXPEDIENT_FK FOREIGN KEY (EXPEDIENT_ESTAT_ID) 
    REFERENCES IPA_EXPEDIENT_ESTAT(ID));

--#229-------------------------------------------------------------------------   
ALTER TABLE IPA_ENTITAT
  ADD LOGO_IMG BLOB;
ALTER TABLE IPA_ENTITAT
  ADD CAPSALERA_COLOR_FONS VARCHAR2(32);
ALTER TABLE IPA_ENTITAT
  ADD CAPSALERA_COLOR_LLETRA VARCHAR2(32);
    
    
