--#261-------------------------------------------------------------------------
ALTER TABLE IPA_METADADA
  ADD VALOR VARCHAR2(255);
ALTER TABLE IPA_METADOCUMENT
  ADD NTI_ORIGEN VARCHAR2(2);
ALTER TABLE IPA_METADOCUMENT
  ADD NTI_ESTELA VARCHAR2(4);
ALTER TABLE IPA_METADOCUMENT
  ADD NTI_TIPDOC VARCHAR2(4);
    
  
--#270: Error al crear interessats de tipus "persona jurídica" 
ALTER TABLE IPA_INTERESSAT MODIFY (NOM NULL);
