INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.arxiu.endpointName', 'Nom del endpoint del plugin de Arxiu', 'ARXIU', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.dadesextpinbal.endpointName', 'Nom del endpoint del plugin de dades externes (PINBAL)', 'DADES_EXT_PINBAL', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.dadesext.endpointName', 'Nom del endpoint del plugin de dades externes (DIR3)', 'DADES_EXT', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.unitats.organitzatives.endpointName', 'Nom del endpoint del plugin de Organismes (DIR3)', 'ORGANISMES', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.pinbal.endpointName', 'Nom del endpoint del plugin de PINBAL', 'PINBAL', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.dades.usuari.endpointName', 'Nom del endpoint del plugin de dades de usuaris', 'USUARIS', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.portafirmes.endpointName', 'Nom del endpoint del plugin de portafirmes', 'PORTAFIRMES', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.conversio.endpointName', 'Nom del endpoint del plugin de conversió de documents', 'CONVERSIO', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.digitalitzacio.endpointName', 'Nom del endpoint del plugin de digitalitzacio', 'DIGITALITZACIO', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.procediment.endpointName', 'Nom del endpoint del plugin de ROLSAC', 'GESCONADM', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.notificacio.endpointName', 'Nom del endpoint del plugin de Notib', 'NOTIB', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.summarize.endpointName', 'Nom del endpoint del plugin de IA', 'SUMMARIZE', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugins.validatesignature.endpointName', 'Nom del endpoint del plugin de validació de firma', 'VALIDATE_SIGNATURE', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.firmaservidor.endpointName', 'Nom del endpoint del plugin de firma en servidor', 'FIRMA_SERVIDOR', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.viafirma.endpointName', 'Nom del endpoint del plugin de ViaFirma', 'FIRMA_VIAFIRMA', 3, 0, 'TEXT', 0,0,0,1,0);

INSERT INTO IPA_CONFIG (KEY, DESCRIPTION, GROUP_CODE, POSITION, JBOSS_PROPERTY, TYPE_CODE, CONFIGURABLE_ORGAN, CONFIGURABLE_ENTITAT_ACTIU, CONFIGURABLE_ORGAN_ACTIU, CONFIGURABLE, CONFIGURABLE_ORG_DESCENDENTS)
VALUES ('es.caib.ripea.plugin.firmasimpleweb.endpointName', 'Nom del endpoint del plugin de Firma Simple REST', 'FIRMA_SIMPLE_WEB', 3, 0, 'TEXT', 0,0,0,1,0);