Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
('0','COMANDA','es.caib.ripea.plugin.comanda.connect.timeout','5000','Temps màxim (ms) per establir la connexió amb comanda',8,'INT','0','0','0','0','0');

Insert into IPA_CONFIG (JBOSS_PROPERTY,GROUP_CODE,KEY,VALUE,DESCRIPTION,POSITION,TYPE_CODE,CONFIGURABLE_ORGAN,CONFIGURABLE_ENTITAT_ACTIU,CONFIGURABLE_ORGAN_ACTIU,CONFIGURABLE,CONFIGURABLE_ORG_DESCENDENTS) values
('0','COMANDA','es.caib.ripea.plugin.comanda.read.timeout','10000','Temps màxim (ms) d''espera de la resposta de comanda',9,'INT','0','0','0','0','0');
