-- Nivell de foscor del tema (0 = clar, 100 = fosc) substituint el booleà MODE_FOSC.
ALTER TABLE IPA_USUARI ADD NIVELL_FOSC NUMBER(3) DEFAULT 0;
UPDATE IPA_USUARI SET NIVELL_FOSC = MODE_FOSC * 100;
ALTER TABLE IPA_USUARI DROP COLUMN MODE_FOSC;
