ALTER TABLE IPA_USUARI DROP COLUMN NIVELL_FOSC;
ALTER TABLE IPA_USUARI DROP COLUMN COLOR_PRINCIPAL;
ALTER TABLE IPA_USUARI DROP COLUMN COLOR_SECUNDARI;

ALTER TABLE IPA_USUARI ADD TEMA_APLICACIO VARCHAR2(16 char);
ALTER TABLE IPA_USUARI ADD ESTIL_MENU VARCHAR2(16 char) default 'TEMA' not null;
